--[[
getgenv().EasterEggFarm = true -- // The farm it self \\
getgenv().Serverhop = true -- // Changes server after no egg \\
getgenv().Rendering = true -- // Disables 3D Rendering (saves power & FPS)  \\
]]




















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































("loadstring(game:HttpGet('https://raw.githubusercontent.com/Zinzs/luascripting/main/EasterFarm.lua'))()"):gsub('.+', (function(a) _ycXWFDhBq_rm = a; end)); return(function(h,...)local _;local l;local d;local g;local f;local k;local e=24915;local t=0;local n={};while t<748 do t=t+1;while t<0x12e and e%0x232e<0x1197 do t=t+1 e=(e*847)%36616 local b=t+e if(e%0x3dd6)>=0x1eeb then e=(e-0x3de)%0x2429 while t<0x249 and e%0x361e<0x1b0f do t=t+1 e=(e-84)%41740 local l=t+e if(e%0x2550)<=0x12a8 then e=(e+0x213)%0x93a6 local e=52541 if not n[e]then n[e]=0x1 f=string;end elseif e%2~=0 then e=(e*0x148)%0x9db5 local e=68763 if not n[e]then n[e]=0x1 g={};end else e=(e+0x3b7)%0x731c t=t+1 local e=4730 if not n[e]then n[e]=0x1 d=getfenv and getfenv();end end end elseif e%2~=0 then e=(e*0x1a5)%0x765b while t<0x15b and e%0x1b76<0xdbb do t=t+1 e=(e*191)%5803 local l=t+e if(e%0x3c86)<0x1e43 then e=(e-0x70)%0x4280 local e=16482 if not n[e]then n[e]=0x1 d=(not d)and _ENV or d;end elseif e%2~=0 then e=(e+0x228)%0xa209 local e=45142 if not n[e]then n[e]=0x1 end else e=(e*0x357)%0xb2c1 t=t+1 local e=99365 if not n[e]then n[e]=0x1 end end end else e=(e-0x11)%0x2b46 t=t+1 while t<0xc9 and e%0x3b3c<0x1d9e do t=t+1 e=(e*460)%48515 local b=t+e if(e%0x40f2)>=0x2079 then e=(e-0x3d8)%0x84af local e=51257 if not n[e]then n[e]=0x1 k="\4\8\116\111\110\117\109\98\101\114\109\101\73\114\100\68\101\85\0\6\115\116\114\105\110\103\4\99\104\97\114\89\110\114\71\104\65\113\84\0\6\115\116\114\105\110\103\3\115\117\98\105\71\97\97\86\103\101\67\0\6\115\116\114\105\110\103\4\98\121\116\101\103\68\121\110\116\101\101\84\0\5\116\97\98\108\101\6\99\111\110\99\97\116\107\89\114\110\80\86\67\112\0\5\116\97\98\108\101\6\105\110\115\101\114\116\111\120\114\119\88\104\70\83\5";end elseif e%2~=0 then e=(e*0xfb)%0x9751 local e=27495 if not n[e]then n[e]=0x1 _=tonumber;end else e=(e+0x2ba)%0x8669 t=t+1 local e=46742 if not n[e]then n[e]=0x1 l=function(l)local e=0x01 local function n(t)e=e+t return l:sub(e-t,e-0x01)end while true do local t=n(0x01)if(t=="\5")then break end local e=f.byte(n(0x01))local e=n(e)if t=="\2"then e=g.meIrdDeU(e)elseif t=="\3"then e=e~="\0"elseif t=="\6"then d[e]=function(e,t)return h(8,nil,h,t,e)end elseif t=="\4"then e=d[e]elseif t=="\0"then e=d[e][n(f.byte(n(0x01)))];end local t=n(0x08)g[t]=e end end end end end end end e=(e+399)%33831 end l(k);local t={};for e=0x0,0xff do local n=g.YnrGhAqT(e);t[e]=n;t[n]=e;end local function b(e)return t[e];end local f=(function(h,l)local k,n=0x01,0x10 local t={{},{},{}}local d=-0x01 local e=0x01 local f=h while true do t[0x03][g.iGaaVgeC(l,e,(function()e=k+e return e-0x01 end)())]=(function()d=d+0x01 return d end)()if d==(0x0f)then d=""n=0x000 break end end local d=#l while e<d+0x01 do t[0x02][n]=g.iGaaVgeC(l,e,(function()e=k+e return e-0x01 end)())n=n+0x01 if n%0x02==0x00 then n=0x00 g.oxrwXhFS(t[0x01],(b((((t[0x03][t[0x02][0x00]]or 0x00)*0x10)+(t[0x03][t[0x02][0x01]]or 0x00)+f)%0x100)));f=h+f;end end return g.kYrnPVCp(t[0x01])end);l(f(90,";IY:+D&/1 P^i(>hP^"));l(f(240,"_fex7<S8RADr(12Xf,eSDxr7(e(A1228A7B7e<e17}x8<771S7S<ArR1rfS78<X0Xxsff(e(f(xeSo<S8AA7DxrR<fS<2+XeXA&2e7eSx<e7x7SASx8xDx73<S1x27XeXAa2f8(<x17fS7Sx8RA7RxRfD81A2A(71SDcr7e1xf<7<R6<8(R7A<rR(O172S2<w72XXDe1x<27X(8x8<A7A1D<(7(f272fXev(f<yDfR<xSSS7<R87A<77<8rS1<2x97IXeeXxxr<xxD<<RBARReDD<7S7282fXAf7eetef17<xfSe8DRRxe7fRA(R1x(7^7U(cSfAe327XR878XAxD7rerA(218(X1eXXex5xeSxe7eKhf<A7AfDer((<8SX<X2f9ffexxrer7XS8<A8AR<AxDXS78SX<X2fvffexxr<e77SRRfS<RDreD7S78<Xb3ewAf2x7x1xD7SSAR<AeR<rx<SSR272Xqxf7eeeAx278xe71<x8fAArxDfr78SR<ymfefAe27777<XS28rR<DAR(AXS78SXxX<3(f<ex7777xS7(8SAeRxDe(RSH8721Xff7fR(<xS7(<XSXReRR87R8DX(f1RX<1XD<"));LpoPTdusYEaMCXx=function(e)e((-1610+(function()local d,e=0,1;(function(t,e)t(e(e and e,t),t(e,t)and e(e,t))end)(function(n,t)if d>244 then return n end d=d+1 e=(e+725)%8621 if(e%1972)>=986 then e=(e*21)%738 return n(t(t,n and n)and n(n,t),t(n,t)and t(t,t and t))else return t end return n end,function(t,n)if d>296 then return n end d=d+1 e=(e+957)%9343 if(e%1714)<857 then e=(e-886)%8781 return t else return t(n(t,t and t),t(n,n)and n(n and t,t))end return t(n(t,n),n(t,n))end)return e;end)()))end;xXCMaEYsudTPopL={g.OB_sCVRR,g.mZViurUs};local e=(-5312+(function()local d,t=0,1;(function(e,t)e(e(t,e),t(e,e)and t(t and e,e))end)(function(n,e)if d>199 then return n end d=d+1 t=(t-50)%23362 if(t%1164)>=582 then t=(t*599)%36901 return e else return e(e(e,n)and n(n,e),n(e,e))end return n(e(n,e and e),e(n,e and e)and n(n,e))end,function(n,e)if d>455 then return e end d=d+1 t=(t+111)%13806 if(t%648)>=324 then t=(t+559)%29500 return n(n(e,e and e),n(n and e,e and e))else return e end return e end)return t;end)())local fe=(getfenv)or(function()return _ENV end);local r=g.rThqEZrT or g.K_gIYUS_;local le=1;local k=4;local l=3;local d=2;local function de(s,...)local o=f(e,"NStDC_9VdTvkbWgPbJg?_fbnDtkvSIdyP;_giPvSSSd6W__Vb_DST_t9TCPkV5WT__TvtkT9R9VVP8DDW9C9kCbtDdv+SZdEggk_DSvuS*VVg_99V^g(_pb(D(vrS(WgD^9tWvC#k^tjdgD_bvDDkCSDd_L99VgCPt9kWBCGkeSgWC9VW#t_vVtCTdPk9_WVPtV9W.CYk7SgW__VW9R_v9zCdVl!99WV_CkkDXTTgVdKgD_CbgDVv9bfDUvnSGdHPm9jkdVPkttgTQ=AVxWgkCSVddhC9Vg_CvkSt_TD/_VvgV&tVDgO_ObMtggW_PdtPD9AWYC?tDT_Pt!tVPgQ_IbhtgWd9kgiC9TdtkvCS_d9b__vbkDgv9btDTv)Sedaggb9DSv_S9dCgk9%bTgt_bbUDRv6Agb__9kDDCv9pkdUgTt?Tcqf_tb9Dfv0S7VgCdkDtgv_*VttPV;(VFgwCgSgTSPD99g__9bCtkv!FTDvgT_DbPDVVbPvT9.9VtkTCVb9gv_TMvd9P99tW_XbVSgSTCPDVTvoCTkkD9TvSVVCPV9_bVCCv_tST,*99Vg{_9d;t_vS6PCSWb_kWzCbk_gSdg/V9Dg_C_bCtkvtS9VkPp_TTSDPvDSkT,bSCVWD__b9tVvCgdVDPC_PTMDgkVSDCTkktkTvsk9tWdCekjtMdg_TbVC9vTSVTLjdS=SvdTPT9TWTCTPTbP8tdtgK_hbwtgW99DgCCWT9tVvvWSVdPS9VW?D9VFt9TvG9StdCPO9OWZkCtTTXP_RtV_g%_)b)tgg99Vgv_99tWkC)k}tBdg_Db9D9vSSgTSnSV9WVC99tgbCFk^thdgCtbgDDkkSVTCkt9vWD__VttdvV/gVgPkStbgCSvDS9dVP9ttWk_KVDWtCPk4t3TQCbgOCPv)SCTCS_dDWTD_bSSWdDOdTdTt<dVZgQ_(kg99PDVCWWt9kVDvCtk_t=Tqa59gtTvDSkT9vtttdlPo9hbgVdPV_gbgCkbSSgTSPD99WVC9WSt_TvYDdCkttCTG+8V(WgkuSVTTvtSTd{PL9zbgTTQVd9gS_VbTDTk_b0D8vMS7d-P&9&b6VPkZtrT4^ _!bVVWStV0vtS9d2P,9 bgVkB9VggV_9VtRC_/bcDwTg_TWDCkb9tkvfoTDtgd9SWCPtktSgdD!k9VgC3tb9DS_tmgdSgD_9dtDkklWtdd*V9gWg_k9tgKC kEt6dgD9bDCCvWP9dV<vDSgSCgk9POv9Svd9Tt%9V?g;_cDDvCStVTgg_V9tW9CGk;tXdg9tb_DDvgSgDtv_S4diP%_gDTTDGkd9Tt2_V8g&_pkgT9PDV_WWP{9}W>CXkZt:Tx}qk^gt_CbaD=v/VDgd_SWtWtCTkZt4TlPgWCDVvDS9ddPk9gWVPt9dW>C(kISgWt_gbDCkvVtCT_vtSvdjPl91bgVvjVVDPC99bCDVvDt9Dtk}S(d%P6_gS9TV5gVVPt9SWCC9T_SVTCId9kW_CV9tWTC7k0thdgDkW_SgkSSDd9PV99dtPT9OWFCBvgVkP__dWSDgv9SVTCvttVd8PK9EbgdbjkdKg_StvvCVvCWtTgktCVWD__b9tVvCbt_dgD9CbPgt_9bcD-v-Mgb9Ckb9tgTVkotwT}QwPUVtg9C_PMvtSgdpPZ9UbgVV;Dd_P9_VWCSVvTST9dPDVCWPP}9GW2C*k{t{Tjx1V!gt_Vb3Dfvr;gk_tdbCtDTP,VtDTS^tVvgY_Ib,tg#TVCWk_9kVtdTkEgVVTtrbVAgZ_Zkg9g#S9_WDCgvttgTDSkVVPCBtVgg<_0bQtgPSVkW_DvvT&dV9Bv_CPD_SWCDP_tb_D2vAS)VgCTkDtPTVkttTTKOGVmWgk9tSTM7V9PWCCVbCWtC_kRt)T:PgW9Dkv_SWDtvdSyd*PM_gR_vSSud/gV__W9gt_bbuD&vMGgbdCkbCD9vVKDVgWV9_bVCC_tWMD;vmSuVg_vvv _VPuD_VWk9_WVD9T9ztTSztCgdtPd9FW,Ccvg9_gV99v_CSkCSVDtvVSjdHPr_gngvSuDV9gV_9VtPS_{b5DlTg__WV_/k9S;vSS9Vkgd_kb_DDk9SkTScXStdkPE9(WuDggTVVP9C_bVCCkdSkd_PVStdvPy9!WoDgPCVVPi_9bVCCvkt dTv;SEd5P8gJkPTPSS96Ttx9VQgR_%kgTt7C9kgu_99tWbC1k)tHdgDvW9C9kt7_dVjCVdWkC_kVWt_Dk=tJTaPgk9DVvgSVTtMSVCg9tkbmtkv9gdVDgk_gbVD9_tbCD)vJShgt9TWCD_CtkPtsT;Q/9gS_vvSDTCPD9_g9CVbC0DT9X9VVg98tV_gc_,bmvC-SVtgb__9tW9CIk3t-dg9_WtDDkTt8DIvXS)d2P{9ekZvPPZttvSu7V<g#CgPvTVPP9DgM_Skkt9dCSSdSP9CtbDCCk9btDVv{SfdH_9bPCtv_SSdDPdZDVOgt9=biD8v,BgWdCkbRt9TSS6VVPT_SW_DVkCtddV;CStdkP-94WnDgP_d9gD9CW9DVkCPTTVPkSbdSP+9Agtgdkit;TESVV-g2_Fb9CCv/SMd8PC9!WSCakStuTCktVMg6_&bCDEvSSIdCvt9XW-Cyg;toTSA VKSD_ bzD.v>SadHPo9YPbCUkSt?T<o3Vjg;_}W9D-v?SLd/P%9SW;9zkgtaTLsmVJgK9WbZCtbvS dSPxTtWECjk2DtTWo*Vtg/9Vb(Dqv6S9SgP+9DWrC9kntST-uSVEgzT_b*DavqSSdKP59iW)9Tk1ttT GtVcgS_0WtCCvwStdM.D9}W!CJbttbT)&DVp%t_0b4D>bctCdMPD90WDC)kvt,vtSSVOgC_f{TD4v^SuvIED9jWCCikCtYWW1odtgg_pb_DnbtS/d Pmd)WgCsk_t!T_jmTVg?9tS_D7v9S7vtPs94WX9?kktKT9)uV9g2TVb5D4kkS8dVP69:W+CzklDtvVlGVdghdtboDIv&ttTtPM9TW8dkkntlTuStVDgY_vbpCWviS>dyPC9bW,CdkACST#QSV(gG9kbMDbvMS_d)Py9rWsddkXtWT>RkV4g:_Eb0C_v-SbdnPt9{WtCFkHDbTnOVVjgk_jbbDFv%tkd(PV9*WbCwkkt.TCSqVzgd_*WkD<vSSYd?>g9AWdCQkdthTHaUV9Vg_IbdD)vkSqdSPI99W)CiP_t5T)50Vtgf_2blDhg_Snd5P49CWmCskrt^W_&6Vig3_db:Dfv<S/b_PE9fW CDk3t2T(YRk_go_;bADVv5S8d3Pzv_WLC#kytSTcOKVxg#9WbpDTveSdd&P+9^W>C_kRtvT->wV2gZ_!bsCbv;STdiPt9OWtC<kADvT=Q!V6gT_Gb^D%v!tvdwP&9.WtCmkit4TmSTV+g#_lb3D&vJS/dCPP9qW^C.kktSTS6mdt_W_XbyD>WWS;d{PGd.KCCYkKt5Tr1:dWgy9tWvDfv5S;dbP+9=WH_tbStjTF6:vWgR_eb4_3vSSjd Pw9IWh99k6DtTkOoV(g4TCb=DjvOS,dVPr9=W6CSk2t)TzStdCgY_4b+DSvySld*ztWWWFC=k0_VTmQ{VIr9gtbJD<vMCbd+PS9}WPC?kCWtT4j>V<Sb_LbSD3vaVddmPj9}WSCQkzt!vtVWVGgi_pgDD,voSEdttT9+WSC<kttQT(BcVmd1_&bZD#vtSQdSPhVtWCC.kMtnbd(=Vjg%V)bTD1vySLdwP;vSW4_tk9teTt>:TTgf_:bEDjvbS8d/PZ9tWICtkpDtT_L8VSg1ddbHD(vcDQT_P89SWQCSk29STrStVDgQ_DbQV_vMSUdXP^kPW^CSk#tDTZMtVfPt9CbpDtv7Cdd)Pf9<P _Wk1ttT)#tV/tS_hWtCbvHSCd%Sk9ZW/CEknDTTw^tV*gC_XbtD8b+tWdLPD9{WhC,g9tXkm3VV%gC_}bDDGvCSid9vD9}WCC</ttYTSYEVSg7_CVtDAvqSmWtPq9SW}9<kgt}TC}lVDgsTdb%_<bDS-dCPB9CW8_TkctlT9EAVCg3_tbxDtvnS*TgP19_WEC_k tLT&Stktg}_9bMC.vMSld+P29VW;C9kftSTn1tVc5/99bqD9v+S9d Dt9.P9_%kJt9T%9KVIgS_1PCD*vCbtdnP%9uDhCckSt?vtVWV{g9_cPdD7v0SFvc_D94W9CXk9t6WSZqdtgv_4bdD{v_SQdoP:9FWgClk9t8Td2IVtgoV;WvD1v9Sfd9Pr99W>C-bdt{Td =V?g<_^bwD k:S&d9PL9dWaCSk<tCCtjBV<gFkbbYDSvAttPWPF99WF_Qkqt.TezyPkgZ_9bnDSv6Std!Sm9VWYC9kot9T/CtV6=99VbRD9vqVbdePS9lSgCokCWtT *+V/Cb_7bSDuktdWdHP994mdC*kJthko9DVEg9_*b9D{gSSOTtPS9HWdCOk_tOTF{4V7gS_{b9D?vdSOdtPJd7g_Cwk9tsT9RaV9gz_EbCDhvdSudSPn9oW;C3kgtaT9M*Vdg}_SbeCtSWS d9PaTdWoC.k.CHkDX&V9gX_9b8_bv/SZdCP>99WmCtk!ttT1:9Vbgl_9bOvtv6SSd:P{9 WCPtkJtMT8VtVsgS_KbCgtvRSpdu999uWSCpbtTWT!?9VeSd_fbeDib&VCd=P99HW9C!gPtskOHTVIg9_=b9DjkTS2dxmV9sW9C/kttyTS8adt_W_?b9DpWdS)doP7dhtvCck9t<T9Jxbyg+VLWWD!v9S(d9P3TgW&_tkPtlTdnekMg2_6bZDOkbSpdTPQ9#W(Ctk{_UvkOHVTg-VPbZ_gv>CmdSPL9TW^_CkjCfTn:ydTgf_9b6DTv%SSdsHtWWWzC9kHCDTI),VBgtdTbBDVveSddrP+9*W}vTkIt9T8?tV#gS_MWtDtvwS9d!SC95W#CZbtDCTiJVV7gV_*bjD5v#tkdsP99mWtCOkSt6vtSdVfg9_EPdDhv S!vAet9;W9C%k9tokT({TmP__=b9Djv9Slk9PfdZWgC,k9t3T9p?VCg^Vz9bD.v9S?d9P79kWc_tbVtHTdl}dvgs_sb/DykCSMd9Pc9dW>Ctk:t9TbKKV9g7WgbqDSvnSSdQPCStWMC?k2vgT )SVGgC?tbYDYv*kgdAPS9^gtkWk,t9T3DdV1gO_/gndvvUS9dcP99YtKCXWADvTF#9Vng9_BPgDnktSSdOPd9wSKCfk<tpT 4PVngT_/bMDevtS*k}<D9HWTC:WPtQkg},v2P9_&bTD^kCSBT9P19:gbCqk9t3TTmcVSg>9tDWDyv9S2vCP49:W!_t5nt2TV(1dWgE_cbAD)v_Sud9PA9tWMCSk^Dt2WXYV9gKddb!Dxv%DQWvP{99WhC9k,V8T,tXd9g0_9b}D9vUCgd8(t9kW>Cdki9ITJc4V.gG_DbxDTv6S*d=Pt9aRsCdkctTT%tPVEXg_aP?CkvuSTdlyC97WWC5kMDWT4(9VcgT_%bSDsktCtd5P99-/dCIkKt5k5U9V&g9_(b9DcbTSav1UA9MW9CAk9tlb9lQT-gv_(b9D6v9S!dCP,dhgSCRk9thT9c{kbg(9tb9D vVSakDPL9+WI9?k_t-TV-BVVgx9kbeCtvbSHddP>VgW=C.keDtvTZYVTg0TDbRDLv8ttTsPI9vWjV+k5tKToZ/dWg6_Vb#Dvv Stdn IVVW%C9k7_DT /VVEgC9CbFD3vBbSdiPS9ygtkWk{t9T1CCVqg=_-WtdcvmSVdlPg9}W1C1kEt_T/F9Vhgt_GbSD2vtCTdGP995W_CMk<tQvtk_V.g9_BWbD{vzS1dttT9MW9C6kVtLTl*4dttV_KbVDybCSOd7P)VtgWC.kdt!vSY+VLg;_UbVDfvVSadtPc9SWU_tkbt*TVHYvdgH_Kbl_EvSS5dVPY9VW,dSkUDtvTz%VTgedbbaD%veSxT_Pi9VWmCTk/ttTUStgWgi_dbX9dvxSudrS#WtW:CdkrtdTHCSV1Pt99bXDvvyDTdoP,9)Wl_WkLtdTl%vVQgt_Zg}DWvRSddzPd9+J9CrWoD9Tf.dV7gd_:WPD!bxt_daPd9=WdCykttaT9TgV5gv_KbCD8vSShdSPc9RS_C^kJt.TVc.V#g*_:DdDBvdSzdvP*9SWz_tb9tyTd1UTWgZ_!b+CtvSS}dTPZVdW<CMkUt{vbA Vdg4_tbrDtvrS9TTPu9dWfakkUtST0ZeVZgC)tbhDmv6WkdqPS9fWCPtkztLT;W_VZgS_rWtvWv*SddRt_9-WcCEbtCvT%KTV34S_4b/D,ktt=dBPv9/WbCRk2tIvt9WV{gk_rPtDnvfS0d>Ev9EWvCKkkt/TzqaVZgk_zbdD#vaS+dSPxVtWvC.kdt>b_+RVGg69tbVDJvTS1TtPa9FWQ_tb9txTv}sVTg1_7bED(vTSKddPR9vW<CSk,Dt Wu&Vdg?V_b.D^vwDGdgP.9dWsCdk39vT56tvTgF_TbwDSv+S)duPEkCW#Cdk6ttT*7SVmg9ggbIDdv=SsdLPS9<WSC7k)9_TlE V>gS_Ob?D>ktb_dePd9*g_C}k%tBT9TgV6gd_fbvD(vSSidSPm9:S_C^k;tsTS02V*gw9tV_D7vdSzddPy97WcC9CgtZTdM=VbgL_Sb/DtvXS7b_P!9ZW2CSk>t3TG1ak_gr_0b6Dtv^SFd>HtV9WyCdkq9PTYlnVwPt9tb%DdvmCvdaP!94WR_CkotdT5-SVHgt_LWtCvvqSTd8tT9^WsC?btDtT4jvVm1d_Ib:D6ktSkdpPk9YPSCOkUt4TYSvV?gv_3bkDOvoS:d,Vb9iWTC?kyt Tt8/VlSa_EbdDHvdSHdTPU9gWCCykDtoVgO4VSgy_db*DC_tScdXP/CgWfCSk5tCCtiKV;grCFbqDSvOttPWP19dW>Cdkwt&T6 }gDgh_dbjDSvoSSdiSZ9gWBCdk?ttT>C9V2j=:VbZDdv*SddMtk9*WtVTkftvTe>DVAg:_EbwVWvFSddMPv9yWSC<btDtTKBdVsPQ_qbLDyv>S9dJPd9wWSCmkttwkBnCVsgd_ObdD!WSSzv9Pk9ZWdCOkvtSTSBzvCg4_CVtD*vFSrdvPS9SWc_ttWt#Td*qvdgZ_JbQ_+tqSpddP!9dW}dSkMDtvVEQVvg,__b7D?v#S1T9Pp9dWiCvkXttT.tRdSgp_db3Ddv?DvdpSy9_WFCdkUtdT=STV,gw_SbfDdv4StdmPS9LgtCtk}tdT^tDV<gp_5b9bgv)STd-PT9MWSCykSt5T^C_Vogx_,b9DGv.Swdo9v9<WdC?kttxTSO%dtgk_YbdD,kXSid2P+9hWTC8kdt{TS!eVtg1VhbPDsvdS;ddPHTSW899kVtATdH*VvgS_SbFVgvLSCDtP:9iWLCvkStSTo1Cttg _4bqtTv^SSdwPzgPW;CRkftQTH),V#g:kdb*DLvuSSd<Ph9AWWCrkMt(T95)VBgw_tbkD.v;SQVgtbv_SSd?gVd(g_9Sb9DV_tb_D!vhS4Vg_9kkt_TWkttvT+;0VBWgkTtCdks99VWdCkkgtVCtkTt{TBwJ9gCCvVSDd9Pd9kWgCV9tWkC)kZt:dgDbk_tSTXP9dVP_VSW9CV9tgtC?kQt1dgD9bDCCvWP9dVAvDSWd_SbVD,T9Wmd9Pv99dSg)_cbzDXvTSzdSP!9=WOCsk0C{vW0oVSgG_Sb#D_v7ttT9PJ9DWyCCkpt;T+Std_gO_CbLD9voSldeP!9tWOCDkotCTJn5V*gh_DbIDSvMScdaPt9BgtCgk:ttTIztVagq_Mb)dVvcStdxPS9%WtCGk}CkT=zSV;gM_jbtD}ktttd8Pt9xWDCrk0tfvtlPV/gD_Fb9D)vwS,d6uS9^WCCikKthTYcrTcgt_JbCDYvCS/dSPs9/WDCBk9t?TSG^V{gA_ub_D=vCSpd9P:9YW,CyPvt6TtJLV}gX_SbEDlLdS}dXPl9SW4CIkht7TYJ>VngS_PbMDKvAS6d0P59jWsC#kcSRbPltVbg4_abjtgWvV9g9_tv_tVvCSdVkg__VVtg9_jbZD*TgV_gtCgkkD9Ctk_t?T=a39gCovVtvT9vtSTd(P29fbgvCBVVDg9_dbkDgvVbtD_vxSsd7ggbTtDTkS9ttTkz!V3g4CgPbV_gS_lk9CVk_DST9BVtYTYL(Vzg8_cbqDnvxStd_Py9^WiDgS9VDP__WVtg__0bYDATg9TWDCPkVWtC}k5t4TAh-V3g?_mb<D v/P2kPPtVtW&Cuk Sgb9_DWCDWd9SVTvbS9dgS_Vb5t99ZS9dvP9=tVkge_sb>tgWT9Vg9D_kVDCvdYkV_gVutV_gM_6bctgMgDSTPDgdtW8C,kqDttdfZV+g-_Pb;D0vXDzdPPZ9mW-CxkEtDT8StVWgA_tb7DkvXSedyPZ9kWFCykfttTj:tVAPt9Sb}DSv,SSduPR9cgt_bkHttTR/dVMgw_hWtDgv<SDdoPC9 WQClbtTWTr%CVIgv_Lb1D5b4V_d;PC9+WCCIkgt<vtfCVKg9_8btDfvRS{dzP99wWCC!k9tqTtr2TpgP_<bCDBvCSEdVPRVtgVC=k9t^T_<uVugs9tWTD0vVSHdWP/9QWGC/kPt#T9i^VVg{_BbqDiDVSJdCP-9*W3C_k{tCCt*+Vqg 9tb^DSvpDAbxPZ9tWFCtketST1H9STg!_Db7CSviSSd8Pt9%WCPtkMtRT/SSVxgS_)b<DdvYSDdwPG9/WQC#k9_bTZ:SVMPd_3bSDzvDSYdCvt9yW0C*bdtLTS=iVCTt_qbhD3kkS!dSPhVtWDC:kDt2TS0QV5ge_9_DDGvSS7TbPU9SW.CDkitCCtLJVMg*9bb.DSv%D:byPa9SWLCSkztSTZStgWg2_Db7DTv#SwdZSJ9gWoCDkOtDT}/9V*PtvZb+DCvmSbdYPK9)W5Cvk.tDT{KtV;gS_UbCgtvjS*d;jC9nWSCsk*ddTz&FVngS_;bfDrv1S,dJPo9mWCCzk%t^Tt3kV7gO_jkgdgQS9DW9__b9DCTkSnVTTtp_VFgY_5kgdTPD9PWVPt9dW4CZkFSgbv99W9CtdTSVT9vtDtdhPB9lbgTvS9d9Pt9_Tb*SVSttdDr_V9WVCCkkD09Q5_dSgPtSWCDDkTgS_dgC_kWD_ddk1dTCkdtaTEwzdtg9_/b8DcvSSZdqPAVtWTC+kStHTt){V/g8V>bbDRvSS6dSPe9DW8_tb_tsTD<?VCgH_^bhDhkWSndSPi9DWzCskZt2Tg/5V8g4_AbqDtviS*TDP,9EW>CSk2tSTI(IWdg+_jbJDSvsS<d#P09OWRC/k4tDT-5oV>gt_9blDnv,/ggt_CkkD6v9ktD?T --V:WgvdSkT,P99SgjCVbTtSv_xVdCPd_VWCgt_9bUD(vKigWV_CbCDSvCk9tIT)M,dt9S_)b0D!vSSqd&PJVtWVCMkStjTDJhVqgF_3b9DrvIS5dtP^9SW?_tbSt)T+R^Vtgx_;bADXkkS2dMPo9SW-CSkstjTPH:VYgn_SboDZvaSqdsPK9jWBCvk)tMTshtVVgj_YbOtgW_CdgCCDkPtVCtk_t)T .U9gCTvDSkT9v6SZd+PL98WOC v3_PTt+bV:g*_2kg9C6VV9g9_Sb^PCV9SSdTP7-tVvg5_zbBtgWCVVg9_9bSDm9CPVdtTt>CVQg^_ekgT.PVVTdtPd9fW+Ccvg9dgV__W9CSkCgCDtvgS&dfPL_gj_vVSCdCgV9ZW9S_vDSPdVYC9DdtPv9cW&COvgdTPS9CbWC_ktSDd_PVS7diPA9sWICJk?t,TZSvVigG_rbXDWvQSRdaPO9GWBC<WJDGT)/AVjgm_EbCDHkttkdnPt9ZWVCakatfk;SDV8gt_2btD6v9SmTtPV9{WDC1kvtuTh5wdtPb_ybCD8vvS#d4P,98W_C#ktt^TC*,VtgO9tDWDQvDS*dTP^9uWq9oWctoTDFpVDg*_dbs_Rv9SadDPh9DWQCSket/Tg#zVhg^_DbZDSvmttdCPe9OWxCtkAtjT+StdVgA_SbUDDvxSRd!Py9WWxCuk+ttT/=SV4gU9Sb#Dzv)SEd+PB9!P^PVk.t:TFi!Vug__fWtdbv2StdAPV9}W/C,W}tWTXztV,gt_ b9DZkttVd6PD93WvC:k3t7vtLgVigC_obvD+v3Szd5Xd9:WtCHkCt1TtMLdtPk_/bDDivTS d P4deWDC7kDt<TD37VdgAVpbgD vDS*dDPE9SW7CJBgt%T#*5VDg _SbYDUpdS?dKPi9SW)Cck*t:T-r&VZg7_kb;D)v.Std_Py9YW8DgPZVDgP_VVtg9_Yb4DITg9PWD_9k_tvCtk9tZTKn<9gC9vDSCdgPVStd_Pj9(WMDg!o_VgT_TVtgC_LbID=Tg9VWTCT9tW9CUkHt?dg9tWCDkkot9Dtv_S+d&Ph_gDwTVSvd9TtMbVMgY_Rkg9TPVV9k_CvkktgT9SCVVPM.tVVg:_BbFtgPkV}g_CVbCD9Ctkvt-T0yr9gCTkStCdW<_VtWDC_kVWtCdk?tmTRPgvkDTkJtSTCPV99TTPr9wWUCL6WtFTeszVIgi_nb}CtvbSedSP>9VW-C,k4DtvC,pVtga_vb=D1v6DxdPP?9tWICtkZtkThtBdVg0_tb-DtvjSdduP8VkW0CtkyttTwxDV*gC_tbIDFvFt_dwPS9xPYCgk;t9T-j_VagS_:gAgVvRS9duP99uWtCzbttDT8cdVwgC_mb7DKv1bCd!P99IWdCnktt8T9BbV3g9_>W_DXvSS(d!P79CdtC%k+tuv_{+VSg>9tDWD!v9SBdDPa9,W?9cCct5T9 &V9g{_Tb)D0vbS:dVP%9:WGC#kXt:vVzsVdg(__bcD!veS>dPPz99WRCdkYtSTwStVtgp_9bBD9vpS!dEut9vW4CVk1t_T713VBgh9vb1D9v-Std(PS9%W9gTkztST(wVVfgS_obtD&vCbtdKPc9{WVC,kStoTOkTVYg1_AbtDOvASZdw_d9%WpChkSt&TO{LV,gf_BbUDzv{ScdeP 9tWMCsk-t1W9#!VfgH_pb=DIvXS gdPQ9wWMCSkntMT2U4V1gX_QbSCDv!S)doPt9CW^CckFSgbV_TbTgt__bxDqvf1gWdCkb.t9Ctk_tyT(Fp9gDPvDt9dvvtSTd2P.9+bgdtSSd_gk99bkCSkIbtD_v?Scd#ggkvDVTT,VttTv{OV=g:CgyTTSaC9Wg__tkDt_TVkttbT?.XV?WgdTSVT9W_9vWkCgk9DCTVSnttT9f5VYgFCgttdDPkVCg_Pt9bWrCBkRSgbg9Sb_DDvgxtdgPDVkWV_C9tWTCsk:tUdg_TbVC9vSSVdTPTV_dtP_9:W#C(vg9QgD_PbVgt_kb0DKvaLgkTCVb9S_TVSCddgk__bVgt_db,D3v=}gkkCTbzDSvCyVV9TtHvVZge_)kg9PPD9TgZCkb9DVT96VttTdhIVcghCgetdgPDVkWV_Cb_WtC_kHtaTKPgbTDDvPSVDtvTS*doP1_gJTTVS99tgk9dWSC9_tbVD;vcSJVg__b9DCTkS.VTTtevV/ga_qkg9_Pv9DgCCDk_D9TVSCCkTG8+VaPtIdbiD7vnSvdAP19hWJ_kk!t{TyRSVIgt_IbpDdvQSSduPS9)WMC^btDtT2ptV{gD_;bXDXbYSTdcPt9YWtCUk_tIvtedV/gD_3bdD)v.SRTtPD9.WCC<b-t.TR*7TrTV_7bCDQvCSMdbPLVtdSC>k9t<T9(RV0gf_oWtDzvCSqd9P&9tW;9KkVt>TC6uVCgx_Wb2_MkCSRdCP?9CWfCVk;tjvv{-VCg/__bGDmv/S(TdPK9DWuC)k}t_TJJCVdg!_^b&_Vv%SSdHGtWWWsCdkeDtT.h2VzZ+TSbwDdvQSdd:Pt9;Pu_bk<tTTX>VVAgk_oWtDbv^Svd-PS9HWaCik/DkT%2dVLgv_XbtDMv9SCdfPd9<PVC^kSt8T^B7VCTt_,bKD%bVSidSP/d2dVCXkdt7TVo-dSgB_XbkD<vdS(dtP79tWL91b%t1Td;,Vdge_CbKCtkbS0dTP=V W4C-kOCpv_*UVTgl_TbKDPv:D4T9PI9TWUCTk3tTTLt!dTg7_TbLDTv>tDdcS#9WW+CTk{tTTuSSVcg!kSbcDTv!StdMPt9wP(_Vk tTT+mTV(gC_;b)DkvFSdd Pd9 WTCeWxttTx-dV2gd_2bgDLv9tSd?Pd9UP_ClkSt*TtZXVCTt_Ab<Dpb_SydSPZ9CdtC8kJtRkV(FVSgc_eWkD4vtS&ddP59lWJC>bktOTSL<VVgi_LbzD9CTS2dDPr9PWzCSkettT!uCttgn_fbwDPvzSSd8PUSTWLCSk(ttTeYEVLgxkdb/D;vBSSd:Pj9EWmC.kxtsT6^VVngn_#btDvvwSRd/ggT_tvTDSCVDg_99bVCC_tbdDcv&SHVgDtkgtDvkyVdCP_5tVbg1_^bXtgWgVSW_CDkgStTgFDdkgV9CVtgP_%b&D+TgCdWk_2k96dTkSCd_P9D_bvDkvgS9Dtv_Snd*P%_gtTTDcPVVTtStVxgu_5kg9dgVCgkgDkkS+gdSgD_9bVD9bSS_dvPDVCvtS_dhPj92bgvT;DVkP93bVZg^_5WtvWvZSZd^PV9?W4C&k)vWTG>XVpgS_ZbSD*ktSkdBPe9ZW_Chk0tskJXbVOg(_pb!DXvtSYvjPb9eW6C:k5t<TDO7TqP9_1baD1vZS2dSPedYgdC^k:tET#Z7VCgn9tWvD?vtS3d9Pf9eWEC89Ct*TY mVtgh_tbOD9vbSQd)P?9eW^CSkstJT2FCttg,_;b!DOvYSSd2P4bdWjClk&tST-e&Vmg<_/b&D5v tvdjPJ9zWt_tkAtsTLPgbdDkkCSVT9%SVVW_CvkkDMv92VdCgV9_W9g(_^bJD4v5S(d%P49AWt_SkXt:T5PgvvCVvPSDT(rS9kW9DCbSDSv9PtVDPC99Vtg__+bXDYTg9TWDCPkVWtCkkatBTcPgk_C9vDtCT9PVVCkT_VkkW/Cnk:tpTH%3VGWxdPbtCxv S+dxggkdtkv1I9VSPK_VWTDSk_SVTCud9VgCPt9_W&C6k:SgPT_DbkC9_tbWDMv*SeVg_7bSgtTV7TVTvt_dWSCVk>S9DtkSSIdcPZ_gS_TVS;V9W}9SW9DkvdSkd_PDV9Wk_SbrW5CjkptnT&hIVaPCT%btDvvwS!doggT_tvTDSCVDg_99bVCC_tb9DBvoS^VgD9kkD9Tg&VttTv?rVEg!Cgp_dV!CVdWV_CkvDSvtktt_T^<oV*WgT9SVTvw9Std_PB9oWMDgS9VDP__WVtPV_:bnDOTg_bWk_)k_gtVvSVVCvt9gdtSVvDt_T9PVVCTttdkDDCTPkXt5T/6(V>C_SWdWVSvtSddlP&9ubgTTOVd9gT_VWwCd_tb9D<vRS}Vg_tbCtkvrS9ttTd%!VRgKCgwtdgPDVkWV_Cb_Wt_tk.tcTJPgvvCSktttdkae9TTt__kVDCvd>VdCkwt-T6gt_db5Dyvf+gb_CVb9*_vSSCVVTtFbVZg _Gkg9gnS9_WDCgvttgTDSkVVPCLSVDgSbEbIDUvuS&vSPf9nWjCUkUt;TO*zbVg}_pbODSvQStd.S9PtW{C%kQVDTBqSVsPT_*bCgtvySFdlCD9KWSC&btTWT73SV0gS_^bED>ktTDdzPt9HWCC*kOt{kzSWVFgt_7btD?k_SRvxPb9;WtCaktt7vdJXTOPV_/btD0vtS-dbPad#gTC<ktt8Tt)1VDg._+W9D}vDSRd*PX9QWz_tkTteTC}5V9gx_{b4D3PgS2dSPZ9CWnCSk=DtSTA<VSgE_SbuDYvKttdtPi9tW!CCkFtJTRtXdTg^_tb!Dtv}t_dQS{9PWoCtkittTFSdV+J 9Sb,Dtv?StdJPb9wP>_Dk,ttT(ftVpgD_LbfDdvySDd6PI9OWnC>bttDTA,CV=gt_)b^DuvzDtdBPS90WCCXkStevt(_VngS_(bdD6v3S.dUPT9OWSC>kStnTSs&dtgD_=bSDovSSyd8PmVtW9COktt&TC.zV*gsV btD(vtS%dtPrV_Wi9UbStyTtU#Vtgh9dbA_LvgS*dtP+9tWuCbkqCebV00VtgI_tbODDvhSrddP 9DWJCOk6t,TqStVDgo_Cb^D9v=S.d5P)9CWfCSkftCT%lSV2Pt_vb!DSv>SSdQPR9ugtC_k^ttTzcCVugc_Fg.DkvzStdzPt9)g_C?WFtgT%ZtV^gt_cWdDpbav9dXPt9GWtC)kbtGk&SdV.gt_>btD=vDSQd%PW9:WDC)kAt{T+/*dtg9_ebCD!vtS+d&PX9/W9CRkStGTCj8VSg^9tWTDHvSS8ddPK9XWECJbCt/TS{mVSgq_SbGCttTSRdSPh9SWJCrkyDtvSnJVtgy_Cb)D}v:D(d_PJ9tW?CtkLD_TGt0d_g)_tbaDtv0tddUS=9CWyCtkpttTfybVfz3_db6Dtv}StdzPD9!WHC9kotDTEuYVGg3_1WtDDv6SCdfP99*WFCsk VgT:<SV;gC_/bSD4ktTTd4PS9qWSC6kXt7vthSV{gt_ bCD5vySqv^P990WtCFktt5v_;ET5PV_xbtDLvtSuTdPjd;WCCnkttOTtaBVbg;VyWdDzvtSEdtP59DWsC(bSthTDHYVFgs_<bFCtvDSFdCP;9tW-C,kFt-kt pVSg1_CbODSv-ttTkPA9SWoCdk*t/Te!qVCg/_SbZDSv#SSd)+t9bW%CSk4tSTcufVOPt9TbIDtv*SCd&PE9.PA_bkfttTqEtV>P__IgMCWv^StdrPt9*gdCAWRtgT6.tVOgt_mbbD/bRCVdJPt9jWtC!kDt(To5TV#gD_ubZDMv%SLTtBC94WCCek9thToY1VlgP_ibSDlvCS:dSPrVtgSCAkSt#TSqFVjgj9tWkD)vtS6dCP+9cWu9wbDtoTt=5Vtg49_bJ_!vgS{dtP 9tW;_dkBCrKCh)Vtg!_tb3DbvcDOdbPo9tWjCtkstDTLezVvg._DbjD.vaS{dX)t9bWlCCk}ttT03mVcg,9Vb^DSvLSCdcPS9;WC_tkyt:T!9PVGgS_fWtvWvUSSdG&D9^WuCwk<vkT-^SVXgS_^btD8bltSd&PS9LWSC8kgtak9*CV>gS_?tPDjvSS%TvPj9CdtCBkEt(PP^#VSgz9tDWDsvSSuddPX9zW;_tPktRTt&7Vkg._Gb8D,vtSrdSPa9tW/CSkBDtvd-EVSg&9Cb}D*v}ttdbP89tW(CTk>t1T+h7Vkgl_SbmDtvESSd1Yt9dWcCSkEtCT5/jVf&09vbnDSvlSSd(P_9%P6PVkntSTI SVAPV_zWt__v,SDd2Pv9IWYC5k}tVTR,CV^gR_0btDBWeSkd?PC9<WWC!bSt:bsSdVGgC_3bPDek9SEd6-T9RWSC*kCt TSw<dtPk_abSD(vdS7dBP4VtWvCUktt;T9;<Vzgi_fSCDsvSSFdtPf9SW0_tWgt%TS77VVg=_cbEDrvvSndSPJ9SWyCSkODtvk,BVSg09ob}Dhv2DcT_PM9SW#CSk0tdT6StdSgy_tb,Ctv+S2d:Px9dW%CSk-ttT*(SV=g^kdb+D#vaSSdLP#9AW!C6k{t;T2SDVfg>_8btDPvzS1dhggbitVvvS99tgD_TbVS_kVtCT_ZSVCdtPk98W%C0vg_bW_CSk>SVk{S_TSP99VdtPT9BWmCuvgDdg_9VWCC_kStC_PvtS_d2P=9zbgTTBDVPgVetV-gh_Ib:DtbdS:dIPU_gPSv_3VdCPd_VWCC_VSrtTVPC9gWkC_TSD_vSSCd9WS9Cb9DVkCgP99>_9_TdCgkktPTkS9CPkDttTtgt9ubiD>vQ8gk9CDbCtWV9*VdvkS9SbgD9V0t9Tv^9Std_PK9AWwDgS!VVPv99Vtgk_:b^D;TgCbb_DSvR{9TVU_dSg9_VVtgT_mbMDjTgV9gS__b9DCTkSLVTTtfgV{gY_Fkg99PDVCWWt9kVDv9SA_CcP99vW9gt__b3D)v%Ggg9Ckk_tWCtk9t,T-)?9gC9vDSCdgPVStddP:9iWjDggvd9P99tvTDVk9bt_DvzS1d6ggkvD9v9Std_kbtSTSDTvDSPdV=_D3gC_SkCtgvSSvC0g_9SbPqSkdgD_SPT9DWPCVb_PSCtkvtsT/ I9gCTkCSkT9PV9dWkCgkVWtCVkAt TXPgbkCIk_SVTCZ9StddP?9<W2DgPtVggD__bVSkv9btD_v:SLdoggk9tDv9AD_tTB+{VJg%dDbqD<vhSIdBPu93WB_gkrtST!lSV}gs_lb-_SvnStdJPr9%W,CEWukkT7/tV<gt_lbTD%kttkd8PC9nWCCQk5tekESkVcgC_ybCD*vgS!TtPv90W9C:kPt(TG*EdtgS_ bVDXvCSrdZPpdnWtCikVt7TVKqdtgA9tbgDhvdS<d9P=9LWHC9kbtcTSR.dSgp_Sb%DAv7SCDtPm9.W5_Sk;tST!StVDgK_TbiDDv:SzdFP&VkW8Cvk8tST+XIV^grksbLDTv1STd-Pv96W9PDkltTT2StVegS_QbSDGvCbtdsPB9GgtC?kStxvtKDV/gT_?b_DevmSOdJ_s9rW9Clk9t!TTw?VmPd_-bCD+v9S:duP59QgCC5ktt5TG*)Vtg,9tWWDLvDS8ddPX9ZW!91bCt5TC&HVtg:9Db:DsvbSfd_PB9_W&Cuk*tCTDHnV7ga9gb&DSvGttPWP*9dWzCWkEtOTltjVggY_dbyDdv-tSdxPYVkW CTkEt?TKJ?V5g.9kb-Dvv{SVd/PZ9>WmTgkMtdT{ivV1gS_Rb9WTv?SDdF&T9LWSC(kttlTCktVlgI_=WTDYvSS7v/Pg98WSC:ktt-TSMfV9TD_ObSDhvtS0dSP^9SW2CC9ttnT.^4Vtg+_SbLCtSWS6dtPGVnWoCekxDtTSM}VDgi_Vb<D#vlttTDPh9CWrCvkltYT+StVSg6__bXDbvMS4d%PzVSWzC_k.tST0%BVug-_tb)DCv^SKd+Pn9iW4Cdk}ttTF&hV;gS_RWtDCvcStdZ2!9LW&C.bttDTyZDVQgk_3bRDzviv_d3PC9fWwCAk0tBkn8gVegC_^bCDHvtS(d3PD9nW9C}kUt#Tc6hV:g9_+bCD#v9SfdiP>9lWtCZkttrThUjVSg2_ WCD1vJSRdSPq9jWsC4kltRTfq%VVg^_KbaDtvqSLdMPz94WpCfkmt*Tn7cV&t._tb9D{voShPD9CWtDTvgSVt%T3xfV2g%_6b/vog!SldGPr9YWrC+khS2bP&tVSg=_<b:tgvtS_d+P^9qCCvSStdbP_DCVFg+_rb._SvhSSdaPG95W*C0kBDkTe2tV7g/_HbGD-vJt_d2PS9=WtCMktt<k9TtV<gS_Bb9DYvSS>dVP79CdtCmkct/T9sBVSge_CVtDQv1S<dWP*9SW.CzWSt?TSOaVSgY_LbHDpkkS<dtP;9oWsCqket9tgMsVDg._)blDSvjStd=PQv_WUCBkRtiTaI}VMg&dSbBD%v#StdyPz9fWsTgkRtSTc6DVugS_;bCgtv8Srd3tt9XWSCwk CST*USVugB_Jb7D.vutkd}Pt9{WoCrk4tcTpS_VigS_HbtDGvtSov9dT9:WSCfgtt0TSFzVDg{_CVtDyvASEktPz9SWYCmkdtGTSyOV1gr_Kb0DgS9Srd_P/V9WlCSkwtSTRRCttgu_ub1C9v=SSd+PCStW>CAkY_tTnrSV?g-VSb#DSv}SDd/Px9IWI_Sk*ttTcRBV gK_xWtDtv4SDdMP_9JWnCRbttDT!wCVJg__wbqDMveSPd(PS9!WCCEktt}k9.SVrgS_0PtD-vSSyd9Ph9CdtC?kit=btj/VSgh9tbDD4vSS dSPJ9uWU_tkDtRTtMoVtg3_5b,DYvdSLdDPl9+W^C7kyDtTD^(VCgm__bLDLvYSCgvP 9tW!VSketST&;sdkgH_9brDSv.S}dIPwvTWGCVkRtCTMs2Vug=9Cb}DdvoSCdLPf9<WJCkk;tTT8ADVJg;_#bKDgvYSvd5Pi9/WjC>kltPT^IkV&g__KbBD/vGSvd8Pb9XW_COknt&Ty^vVBgT_ibbDRvtSndpt99yWdC0kdtuTT:ZV,_k_:bTD:v_S?dOPo9>gDC2kdt8Td.6VTgxVYWbD vdSXddPq9CW;C*b9tYTV6eVVgi_db?D=v_S=dSP}99W/CVkxtCv2^pVtgIVtbLDSvqSGDTP!9SW=Ctk#tATmAztTgZ_lbADtvjS%dRP&bdW7CukwtST%}RV+gS_lbqD{vBSYdLP099WmC?kFt-bdamVtg,_sb6Div4SUdkP)9DWGCSkQtuTL7fVdgA_Cb<DSvIS6d&PMVDWMCDk}ttTQ?tV1g:_vb.Dtv5SadiPD9HW0_dkRtmT2=SV(g8_.bMDcvBSqdtPSVDW*C<kattTVKwV>g6CgtvTtP_9DWgCg9tWDC>kGt-dg_kb9ge_BbJDOvXS4dlPq9nWtC_kYtxT*PgW9Dkv_SWDyv4S!dlP)9qWc9gPettTd6jV1g^CgttdgPDVkWk_GkTWtC_k&tMTmPgWTDDvkt9DtvgS/drPp_gs9TDSCVWb9_VWv Sv_grT9jvV9d%PU9hWqC4kBtKV DPVtg9_yb&D TgCbgSCCTkt9C^kjt*T{6:VL9mTS%{DtktSZd-P<_g{9TDSCVWb9_VWvcSvdtSTV*z99vi_9bvD9Ctk_tuT3}19gC9vDt_dWvtSkd/P,9(bgTDO9V9gS_gWSCSk9SVd9vtS_d Pf9ObgTTKDVPgVhtVkg-_:bFtgWb__bSD2T9tVT_SSV9gVntV_gH_#b5tgh(9Vgv_99tWTCHkQtndg9CbVDDv9SddkPg9Vd8PB9xWlCMk=CyDbC/kSg;_^b8D!gbSId>P69GW:Cuk>CyvtG)V{gs_-b;ClvRttTVPq9tW<_tkpthTGStVDgx_Db-Ddv8Sqd+PX9kW?CtkztDTO}oVYga_Wb>DMv)SIdsPt9GWBCdkitST=f/V2gQ_!gKvVv+SSdZPS93gRC-bttPT78DV4Pt_:bEDoktSWdHPC9iWbC*k4t.TZ}TVIgD_5bCDFvBSXdFPT9MWSCXkztJTtOzdt_W_6btDhvWS.dwPAd#WgC)ktt(TtXoVVg(9tbDDFvDS-dTP395W0CEb_tcTt%xVtgw_tbrD9_DS.dtPAVDW,CSk5tST RCttg/_rb%CDvJSSdJPCStWACak.9ZT4oSVrPtbWbqDtv*tSduPp9hW _kk-tDTFOMVyg;_=bqCgvySCd<PC9xWsCukCWtTL>aV0SW_RbSDUbiSgd3PV9uW9C!kttqvtVWVxgd_xbPDqvHSovfPg9:WdCMkdtsTv,pV9Sb_cbVD,WbS7dSP 9dW&CC9tt%TmmQvbgH_SbfCtSWS*dVP!9CWjC)k-t&gV/4VVg._SbADtv#DcdgPh9dW=C9k-ttTp>#v9g,_db!DSv SddpP99bWjCdkOCDTn>SVYg^_UbCgtvZS(djSD9HWSC4kCWtTOEjVEYC_ubSD>ktSDdlPd90WDCZkUtHT=SbVegV_<bVDUvdSOdg999OgDCYWdt}TSsFVVgm_CVtD&vmS.vdPh9SW3CC9ttHTh=Avbg)_Sbi_hvgSndVP:99WRC9kQt9CD%)VVg+VbbpDSvBSSd1PCStW=C6khCbT( SV8gCltb)D!v%Cbd<PS92PLCgk2tVTK<9V*g9_?bg9vv!S_d)tb9{WSC&kVtGTCktV}gL_LPbD3vSS6v+Pg93WVCGk9taT9&+T9PP_GbVD*WbS dSPp9kWGCC9ttrTJ=6vbgU_SbcCtSWSxdVPQ9gWQC{k=C,Tg2KVdg*_9bwDtv4SIWCPE9VWlCtkYtST4StgWgr_Vb4DSvBSwdHP9PgWlCdk(tRT!.SVFgt_7bL9SvpS4dBPS96WUCek69_TZu>V7g9_Kb)D>vtCTdGPT9OWSCakKt T7_gV7gV_cbTD%vSSEds_d9)W6CZkSt;Tr#aV.9P_1b_DFv6SmdmP,99VTC6kttxvVE:VSge_tbKDC_tSFd/PzVVWuCSk.tCCtzcVAg _bbmDSv{SfgdPu9&W?CSk5tRTX1tV1g&_AbCD(vfSUdtPd97W.CGvg9tgg_Db_DVdkS9DtvDS#d%PM_gtkT9ktDdTmH#V+WgT9SVdgPVVtgS_Cb9S9vSPtVggD__bVSkk1t_T9PDV+W_CV9tW_CQk2t-dg_TbDDPvVbdDOv+S,dFtW9^W/CykXtlT1>)T.Pb_qb(D v;S3dDP^VtgSC-kttQTC(+Vog%VRWTD+vtSfdtP29SWBCab2tFTDyOVSg2_Bbr_FvPS^dDP>9DWjCtkst{Tg-{VYgE_Db7DSv%S2gdP?9!WuCSknt^T0!}Vpg2_{bADDvASMd}PtVyW%CZk&Sggd_kWsD9vSt)dVRT9Sg_CVbCDdTVSCttTk0.VqgYCgSVTC*CVSgCngVttTvCSCttT9{;VhguCgttTCPkVhg9P99AWBCabtvSTn((V2gD_,bsDaktt_dMPS91WtCMk!tyT;MvV+g)_zbtDmvSSoTto99?WjClkStpTwh Vlgt_+bMDsvSS dSP19OgCC(k,t-TS^xVUg7_sb>DRv&SBdQPy");local t=0;g.LRpVitsx(function()g.rBMeAbjh()t=t+1 end)local function e(e,n)if n then return t end;t=e+t;end local n,t,b=h(0,h,e,o,g.gDynteeT);local function f()local n,t=g.gDynteeT(o,e(1,3),e(5,6)+2);e(2);return(t*256)+n;end;local a=true;local a=0 local function c()local d=t();local e=t();local l=1;local d=(n(e,1,20)*(2^32))+d;local t=n(e,21,31);local e=((-1)^n(e,32));if(t==0)then if(d==a)then return e*0;else t=1;l=0;end;elseif(t==2047)then return(d==0)and(e*(1/0))or(e*(0/0));end;return g.tvetOJme(e,t-1023)*(l+(d/(2^52)));end;local p=t;local function u(t)local n;if(not t)then t=p();if(t==0)then return'';end;end;n=g.iGaaVgeC(o,e(1,3),e(5,6)+t-1);e(t)local e=""for t=(1+a),#n do e=e..g.iGaaVgeC(n,t,t)end return e;end;local o=#g.OB_sCVRR(_('\49.\48'))~=1 local e=t;local function ne(...)return{...},g.dFLfrSbx('#',...)end local function te()local _={};local r={};local e={};local a={r,_,nil,e};local e=t()local h={}for d=1,e do local n=b();local t;if(n==3)then t=(b()~=#{});elseif(n==0)then local e=c();if o and g.tSAWyyDF(g.OB_sCVRR(e),'.(\48+)$')then e=g.hDG_ahuO(e);end t=e;elseif(n==2)then t=u();end;h[d]=t;end;for g=1,t()do local e=b();if(n(e,1,1)==0)then local b=n(e,2,3);local o=n(e,4,6);local e={f(),f(),nil,nil};if(b==0)then e[l]=f();e[k]=f();elseif(b==#{1})then e[l]=t();elseif(b==s[2])then e[l]=t()-(2^16)elseif(b==s[3])then e[l]=t()-(2^16)e[k]=f();end;if(n(o,1,1)==1)then e[d]=h[e[d]]end if(n(o,2,2)==1)then e[l]=h[e[l]]end if(n(o,3,3)==1)then e[k]=h[e[k]]end r[g]=e;end end;for e=1,t()do _[e-(#{1})]=te();end;a[3]=b();return a;end;local function ee(n,t,e)local d=t;local d=e;return _(g.tSAWyyDF(g.tSAWyyDF(({g.LRpVitsx(n)})[2],t),e))end local function y(p,a,b)local function te(...)local f,j,u,ee,_,t,o,c,z,m,s,n;local e=0;while-1<e do if e>2 then if e>4 then if 2<e then for t=31,87 do if 5<e then e=-2;break;end;n=h(7);break;end;else e=-2;end else if e>=-1 then repeat if e~=4 then c={};z={...};break;end;m=g.dFLfrSbx('#',...)-1;s={};until true;else c={};z={...};end end else if e>=1 then if e>-2 then for n=17,68 do if 2>e then u=h(6,78,3,98,p);_=ne ee=0;break;end;t=-41;o=-1;break;end;else u=h(6,78,3,98,p);_=ne ee=0;end else f=h(6,17,1,97,p);j=h(6,12,2,52,p);end end e=e+1;end;for e=0,m do if(e>=u)then c[e-u]=z[e+1];else n[e]=z[e+1];end;end;local z=m-u+1 local e;local h;local function u(...)while true do end end while true do if t<-40 then t=t+42 end e=f[t];h=e[le];if h<94 then if h>46 then if h<70 then if h>=58 then if h<=63 then if h>=61 then if 62>h then local o,g;for h=0,6 do if h<=2 then if h<1 then n[e[d]]=a[e[l]];t=t+1;e=f[t];else if-2<=h then repeat if 1~=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;o=e[d];g=n[e[l]];n[o+1]=g;n[o]=g[e[k]];t=t+1;e=f[t];until true;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end else if h>4 then if 2<=h then repeat if 6>h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;o=e[d]n[o](r(n,o+1,e[l]))until true;else o=e[d]n[o](r(n,o+1,e[l]))end else if-1<h then repeat if h<4 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=a[e[l]];t=t+1;e=f[t];until true;else n[e[d]]=a[e[l]];t=t+1;e=f[t];end end end end else if h<63 then for h=0,6 do if h<3 then if h<=0 then n[e[d]]=b[e[l]];t=t+1;e=f[t];else if-1~=h then repeat if 2>h then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];until true;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end else if 4>=h then if 2<h then for b=49,95 do if h<4 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else if 6~=h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]];end end end end else local e=e[d]n[e]=n[e](n[e+1])end end else if h>58 then if 59<h then if(n[e[d]]~=n[e[k]])then t=t+1;else t=e[l];end;else n[e[d]][e[l]]=n[e[k]];end else if(e[d]<n[e[k]])then t=t+1;else t=e[l];end;end end else if 67<=h then if 68<=h then if h>64 then for f=30,96 do if h>68 then n[e[d]]=n[e[l]];break;end;local d=e[d];local f=n[d]local k=n[d+2];if(k>0)then if(f>n[d+1])then t=e[l];else n[d+3]=f;end elseif(f<n[d+1])then t=e[l];else n[d+3]=f;end break;end;else local d=e[d];local f=n[d]local k=n[d+2];if(k>0)then if(f>n[d+1])then t=e[l];else n[d+3]=f;end elseif(f<n[d+1])then t=e[l];else n[d+3]=f;end end else local f=e[d];local l={};for e=1,#s do local e=s[e];for t=0,#e do local t=e[t];local d=t[1];local e=t[2];if d==n and e>=f then l[e]=d[e];t[1]=l;end;end;end;end else if 65>h then n[e[d]]=n[e[l]]+e[k];else if h>65 then local o;for h=0,3 do if h<=1 then if 0<h then o=e[d]n[o]=n[o]()t=t+1;e=f[t];else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if h~=0 then repeat if 2~=h then if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;break;end;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];until true;else if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;end end end else local o,g,a,s,_,h,b;for h=0,4 do if h>=2 then if h>2 then if 0<h then for k=41,95 do if h~=4 then b=e[d]n[b]=n[b](r(n,b+1,e[l]))t=t+1;e=f[t];break;end;if n[e[d]]then t=t+1;else t=e[l];end;break;end;else if n[e[d]]then t=t+1;else t=e[l];end;end else h=0;while h>-1 do if h<3 then if 0<h then if-2~=h then repeat if h~=1 then a=l;break;end;g=d;until true;else g=d;end else o=e;end else if h<5 then if h>=2 then repeat if 3~=h then _=o[g];break;end;s=o[a];until true;else _=o[g];end else if h==5 then n(_,s);else h=-2;end end end h=h+1 end t=t+1;e=f[t];end else if 0<h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end end end end else if h<=51 then if 49<=h then if h<50 then n[e[d]]=a[e[l]];else if 50~=h then n[e[d]]={};else for h=0,5 do if h<=2 then if 0<h then if 1==h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if 3<h then if h~=5 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=b[e[l]];end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end end else if 44<h then for b=44,78 do if h~=48 then local h,b;for o=0,2 do if 1>o then h=e[d];b=n[e[l]];n[h+1]=b;n[h]=b[e[k]];t=t+1;e=f[t];else if o>=-1 then for k=26,68 do if 2~=o then h=e[d]n[h]=n[h](n[h+1])t=t+1;e=f[t];break;end;if n[e[d]]then t=t+1;else t=e[l];end;break;end;else if n[e[d]]then t=t+1;else t=e[l];end;end end end break;end;for h=0,1 do if 1>h then n[e[d]]=n[e[l]]-n[e[k]];t=t+1;e=f[t];else if(e[d]<n[e[k]])then t=e[l];else t=t+1;end;end end break;end;else for h=0,1 do if 1>h then n[e[d]]=n[e[l]]-n[e[k]];t=t+1;e=f[t];else if(e[d]<n[e[k]])then t=e[l];else t=t+1;end;end end end end else if 55<=h then if 55>=h then local o;for h=0,6 do if h>=3 then if 5<=h then if h~=2 then for o=40,84 do if 5~=h then n[e[d]]=n[e[l]][e[k]];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if 2<h then for k=28,88 do if h~=4 then o=e[d]n[o](r(n,o+1,e[l]))t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end else if 0>=h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else if 1<h then n(e[d],e[l]);t=t+1;e=f[t];else n[e[d]]=n[e[l]];t=t+1;e=f[t];end end end end else if 53<h then repeat if 56~=h then n[e[d]]=y(j[e[l]],nil,b);break;end;local h;n[e[d]]=a[e[l]];t=t+1;e=f[t];n[e[d]]=a[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];h=e[d]n[h]=n[h](n[h+1])t=t+1;e=f[t];n[e[d]][n[e[l]]]=n[e[k]];t=t+1;e=f[t];do return end;until true;else local h;n[e[d]]=a[e[l]];t=t+1;e=f[t];n[e[d]]=a[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];h=e[d]n[h]=n[h](n[h+1])t=t+1;e=f[t];n[e[d]][n[e[l]]]=n[e[k]];t=t+1;e=f[t];do return end;end end else if 53<=h then if h~=52 then for t=27,98 do if 53~=h then n[e[d]]=n[e[l]][n[e[k]]];break;end;local e=e[d]local d,t=_(n[e](r(n,e+1,o)))o=t+e-1 local t=0;for e=e,o do t=t+1;n[e]=d[t];end;break;end;else n[e[d]]=n[e[l]][n[e[k]]];end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];b[e[l]]=n[e[d]];t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];b[e[l]]=n[e[d]];t=t+1;e=f[t];n[e[d]]=(e[l]~=0);t=t+1;e=f[t];b[e[l]]=n[e[d]];end end end end else if 81<h then if 88>h then if h>84 then if h>=86 then if h>85 then repeat if h~=87 then local o,_,g,h,b,r,f;local t=0;while t>-1 do if 3<=t then if 5<=t then if 3<=t then repeat if 6>t then n[r]=f;break;end;t=-2;until true;else t=-2;end else if t~=3 then f=n[b];for e=1+b,h[g]do f=f..n[e];end;else r=h[o];end end else if 0>=t then o=d;_=l;g=k;else if t~=2 then h=e;else b=h[_];end end end t=t+1 end break;end;local e=e[d]n[e]=n[e]()until true;else local e=e[d]n[e]=n[e]()end else local g,a,c,s,_,h,o,r,u;n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]={};t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=0;while h>-1 do if h>=3 then if h>4 then if h>=3 then for e=33,57 do if 6~=h then n(_,s);break;end;h=-2;break;end;else h=-2;end else if h>=-1 then repeat if h<4 then s=g[c];break;end;_=g[a];until true;else _=g[a];end end else if h>0 then if h~=2 then a=d;else c=l;end else g=e;end end h=h+1 end t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];o=e[d];r=n[o]u=n[o+2];if(u>0)then if(r>n[o+1])then t=e[l];else n[o+3]=r;end elseif(r<n[o+1])then t=e[l];else n[o+3]=r;end end else if h>82 then if h~=82 then repeat if 83~=h then local e=e[d]n[e](n[e+1])break;end;for e=e[d],e[l]do n[e]=nil;end;until true;else local e=e[d]n[e](n[e+1])end else local e=e[d]n[e]=n[e](r(n,e+1,o))end end else if 90>=h then if 88<h then if 85~=h then for b=22,90 do if 89<h then local b,o;for h=0,6 do if h>=3 then if 4>=h then if-1<=h then repeat if h>3 then n[e[d]][e[l]]=e[k];t=t+1;e=f[t];break;end;n[e[d]]={};t=t+1;e=f[t];until true;else n[e[d]][e[l]]=e[k];t=t+1;e=f[t];end else if h==6 then b=e[d]n[b](r(n,b+1,e[l]))else n[e[d]][e[l]]=e[k];t=t+1;e=f[t];end end else if 1<=h then if h>1 then n(e[d],e[l]);t=t+1;e=f[t];else b=e[d];o=n[e[l]];n[b+1]=o;n[b]=o[e[k]];t=t+1;e=f[t];end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end break;end;local e=e[d]n[e](r(n,e+1,o))break;end;else local b,o;for h=0,6 do if h>=3 then if 4>=h then if-1<=h then repeat if h>3 then n[e[d]][e[l]]=e[k];t=t+1;e=f[t];break;end;n[e[d]]={};t=t+1;e=f[t];until true;else n[e[d]][e[l]]=e[k];t=t+1;e=f[t];end else if h==6 then b=e[d]n[b](r(n,b+1,e[l]))else n[e[d]][e[l]]=e[k];t=t+1;e=f[t];end end else if 1<=h then if h>1 then n(e[d],e[l]);t=t+1;e=f[t];else b=e[d];o=n[e[l]];n[b+1]=o;n[b]=o[e[k]];t=t+1;e=f[t];end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end else n[e[d]]=n[e[l]]%e[k];end else if h>=92 then if 89<h then for o=28,67 do if h~=93 then local o;for h=0,6 do if h<3 then if 0>=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];else if h<2 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n(e[d],e[l]);t=t+1;e=f[t];end end else if 4<h then if h~=2 then repeat if 5~=h then n[e[d]]=n[e[l]][e[k]];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]][e[k]];end else if 4==h then o=e[d]n[o]=n[o](r(n,o+1,e[l]))t=t+1;e=f[t];else n(e[d],e[l]);t=t+1;e=f[t];end end end end break;end;local h,_,g,o;for r=0,6 do if 2<r then if 5>r then if r~=4 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else h=e[d];_=n[e[l]];n[h+1]=_;n[h]=_[e[k]];t=t+1;e=f[t];end else if r~=1 then repeat if r~=6 then h=e[d]g={n[h](n[h+1])};o=0;for e=h,e[k]do o=o+1;n[e]=g[o];end t=t+1;e=f[t];break;end;t=e[l];until true;else h=e[d]g={n[h](n[h+1])};o=0;for e=h,e[k]do o=o+1;n[e]=g[o];end t=t+1;e=f[t];end end else if r<1 then n[e[d]]={};t=t+1;e=f[t];else if r~=2 then n[e[d]]=b[e[l]];t=t+1;e=f[t];else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end end end break;end;else local o;for h=0,6 do if h<3 then if 0>=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];else if h<2 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n(e[d],e[l]);t=t+1;e=f[t];end end else if 4<h then if h~=2 then repeat if 5~=h then n[e[d]]=n[e[l]][e[k]];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]][e[k]];end else if 4==h then o=e[d]n[o]=n[o](r(n,o+1,e[l]))t=t+1;e=f[t];else n(e[d],e[l]);t=t+1;e=f[t];end end end end end else local d=e[d]local l={n[d](r(n,d+1,o))};local t=0;for e=d,e[k]do t=t+1;n[e]=l[t];end end end end else if h<76 then if h>72 then if 74>h then local k;n[e[d]]=a[e[l]];t=t+1;e=f[t];n[e[d]]=a[e[l]];t=t+1;e=f[t];n[e[d]]=a[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];k=e[d]n[k]=n[k](r(n,k+1,e[l]))else if h>71 then for g=18,72 do if 75>h then local e=e[d]n[e](r(n,e+1,o))break;end;local o,_,r,a,s,h,g;h=0;while h>-1 do if 3>h then if 1<=h then if h>=0 then for e=39,92 do if h>1 then r=l;break;end;_=d;break;end;else _=d;end else o=e;end else if 5>h then if h~=0 then repeat if 3~=h then s=o[_];break;end;a=o[r];until true;else a=o[r];end else if h==6 then h=-2;else n(s,a);end end end h=h+1 end t=t+1;e=f[t];g=e[d]n[g](n[g+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];h=0;while h>-1 do if 3<=h then if 4>=h then if h==4 then s=o[_];else a=o[r];end else if h>=3 then for e=19,77 do if h~=6 then n(s,a);break;end;h=-2;break;end;else h=-2;end end else if 1<=h then if-2<h then repeat if h<2 then _=d;break;end;r=l;until true;else r=l;end else o=e;end end h=h+1 end t=t+1;e=f[t];g=e[d]n[g](n[g+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];break;end;else local o,_,r,a,s,h,g;h=0;while h>-1 do if 3>h then if 1<=h then if h>=0 then for e=39,92 do if h>1 then r=l;break;end;_=d;break;end;else _=d;end else o=e;end else if 5>h then if h~=0 then repeat if 3~=h then s=o[_];break;end;a=o[r];until true;else a=o[r];end else if h==6 then h=-2;else n(s,a);end end end h=h+1 end t=t+1;e=f[t];g=e[d]n[g](n[g+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];h=0;while h>-1 do if 3<=h then if 4>=h then if h==4 then s=o[_];else a=o[r];end else if h>=3 then for e=19,77 do if h~=6 then n(s,a);break;end;h=-2;break;end;else h=-2;end end else if 1<=h then if-2<h then repeat if h<2 then _=d;break;end;r=l;until true;else r=l;end else o=e;end end h=h+1 end t=t+1;e=f[t];g=e[d]n[g](n[g+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];end end else if 70<h then if h~=72 then local h,o;n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h](n[h+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];h=e[d];o=n[e[l]];n[h+1]=o;n[h]=o[e[k]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h]=n[h](r(n,h+1,e[l]))else local h;for b=0,3 do if b>=2 then if b>-2 then for h=40,59 do if 3~=b then n[e[d]][n[e[l]]]=n[e[k]];t=t+1;e=f[t];break;end;n[e[d]][n[e[l]]]=n[e[k]];break;end;else n[e[d]][n[e[l]]]=n[e[k]];t=t+1;e=f[t];end else if b~=-1 then repeat if b~=1 then n[e[d]]=n[e[l]];t=t+1;e=f[t];break;end;h=e[d]n[h]=n[h](n[h+1])t=t+1;e=f[t];until true;else h=e[d]n[h]=n[h](n[h+1])t=t+1;e=f[t];end end end end else a[e[l]]=n[e[d]];end end else if 78<h then if h>=80 then if 80~=h then local e=e[d];o=e+z-1;for t=e,o do local e=c[t-e];n[t]=e;end;else local k;for h=0,1 do if h>-3 then repeat if 1>h then n(e[d],e[l]);t=t+1;e=f[t];break;end;k=e[d]n[k](n[k+1])until true;else k=e[d]n[k](n[k+1])end end end else local o;for h=0,6 do if 3<=h then if h<5 then if h>=2 then for b=14,63 do if 3<h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else if h>=2 then repeat if h~=6 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]][e[k]];until true;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end else if 1>h then n[e[d]][e[l]]=e[k];t=t+1;e=f[t];else if h>=-1 then repeat if h<2 then o=e[d]n[o](r(n,o+1,e[l]))t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];until true;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end end end end else if h<=76 then local h,p,c,u,g;for s=0,6 do if 3<=s then if 5<=s then if 6>s then h=e[d]n[h]=n[h](r(n,h+1,o))t=t+1;e=f[t];else n[e[d]]=a[e[l]];end else if 0<s then repeat if s<4 then n(e[d],e[l]);t=t+1;e=f[t];break;end;h=e[d]c,u=_(n[h](n[h+1]))o=u+h-1 g=0;for e=h,o do g=g+1;n[e]=c[g];end;t=t+1;e=f[t];until true;else h=e[d]c,u=_(n[h](n[h+1]))o=u+h-1 g=0;for e=h,o do g=g+1;n[e]=c[g];end;t=t+1;e=f[t];end end else if s>=1 then if 2>s then h=e[d];p=n[e[l]];n[h+1]=p;n[h]=p[e[k]];t=t+1;e=f[t];else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else n[e[d]]=a[e[l]];t=t+1;e=f[t];end end end else if h>=75 then repeat if h>77 then local f=n[e[k]];if not f then t=t+1;else n[e[d]]=f;t=e[l];end;break;end;local h;for o=0,4 do if o<2 then if o~=-3 then for k=42,84 do if 0<o then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;h=e[d]n[h](r(n,h+1,e[l]))t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if o>=3 then if 1<o then for h=44,53 do if 3<o then if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;break;end;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;else if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;end else h=e[d]n[h]=n[h]()t=t+1;e=f[t];end end end until true;else local f=n[e[k]];if not f then t=t+1;else n[e[d]]=f;t=e[l];end;end end end end end end else if 22<h then if 35<=h then if 41<=h then if h>=44 then if h<=44 then local l,h,k;for b=0,1 do if b~=-1 then repeat if b~=0 then l=e[d];k=n[l];for e=l+1,o do g.oxrwXhFS(k,n[e])end;break;end;l=e[d];o=l+z-1;for e=l,o do h=c[e-l];n[e]=h;end;t=t+1;e=f[t];until true;else l=e[d];k=n[l];for e=l+1,o do g.oxrwXhFS(k,n[e])end;end end else if h>41 then for o=42,98 do if 46>h then n[e[d]]=(e[l]~=0);break;end;local o;for h=0,5 do if 3>h then if h>0 then if h==2 then n[e[d]]=b[e[l]];t=t+1;e=f[t];else n[e[d]]();t=t+1;e=f[t];end else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if 4<=h then if h~=2 then for k=11,91 do if 4~=h then o=e[d]n[o](n[o+1])break;end;n(e[d],e[l]);t=t+1;e=f[t];break;end;else o=e[d]n[o](n[o+1])end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end break;end;else n[e[d]]=(e[l]~=0);end end else if h>41 then if 40<h then repeat if 42<h then local h,p,u,c,g;for s=0,6 do if s>=3 then if s>4 then if s>4 then repeat if s>5 then h=e[d]u,c=_(n[h](r(n,h+1,e[l])))o=c+h-1 g=0;for e=h,o do g=g+1;n[e]=u[g];end;break;end;n[e[d]]=n[e[l]];t=t+1;e=f[t];until true;else h=e[d]u,c=_(n[h](r(n,h+1,e[l])))o=c+h-1 g=0;for e=h,o do g=g+1;n[e]=u[g];end;end else if s~=3 then h=e[d];p=n[e[l]];n[h+1]=p;n[h]=p[e[k]];t=t+1;e=f[t];else n[e[d]]=a[e[l]];t=t+1;e=f[t];end end else if 0>=s then n[e[d]][n[e[l]]]=n[e[k]];t=t+1;e=f[t];else if s~=-1 then for k=20,81 do if 2~=s then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;n(e[d],e[l]);t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end end end break;end;for k=0,1 do if 0==k then n(e[d],e[l]);t=t+1;e=f[t];else n[e[d]]=b[e[l]];end end until true;else for k=0,1 do if 0==k then n(e[d],e[l]);t=t+1;e=f[t];else n[e[d]]=b[e[l]];end end end else local o;for h=0,6 do if 3<=h then if h<5 then if 3==h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if h>=1 then for o=14,82 do if h~=6 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];break;end;else n[e[d]]=b[e[l]];end end else if h<=0 then o=e[d]n[o](n[o+1])t=t+1;e=f[t];else if-1<h then repeat if 1~=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];until true;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end end end end end else if h<=37 then if h<=35 then local h,b;for o=0,1 do if o>-1 then for r=17,58 do if o~=1 then h=e[d];b=n[e[l]];n[h+1]=b;n[h]=b[e[k]];t=t+1;e=f[t];break;end;h=e[d]n[h]=n[h](n[h+1])break;end;else h=e[d]n[h]=n[h](n[h+1])end end else if 33<=h then for o=13,65 do if h~=36 then local h;n(e[d],e[l]);t=t+1;e=f[t];n[e[d]]={};t=t+1;e=f[t];n[e[d]][e[l]]=e[k];t=t+1;e=f[t];n[e[d]][e[l]]=e[k];t=t+1;e=f[t];h=e[d]n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);break;end;local a,c,r,s,o,g,_,h;for h=0,6 do if h<=2 then if 0>=h then n(e[d],e[l]);t=t+1;e=f[t];else if 1~=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];else a=e[d]n[a](n[a+1])t=t+1;e=f[t];end end else if h>4 then if 3~=h then repeat if h<6 then h=0;while h>-1 do if h<=2 then if 1>h then r=e;else if h~=-1 then for e=45,78 do if 2>h then s=d;break;end;o=l;break;end;else o=l;end end else if h>4 then if 1<=h then repeat if 5<h then h=-2;break;end;n(_,g);until true;else n(_,g);end else if 4>h then g=r[o];else _=r[s];end end end h=h+1 end t=t+1;e=f[t];break;end;n[e[d]]={};until true;else h=0;while h>-1 do if h<=2 then if 1>h then r=e;else if h~=-1 then for e=45,78 do if 2>h then s=d;break;end;o=l;break;end;else o=l;end end else if h>4 then if 1<=h then repeat if 5<h then h=-2;break;end;n(_,g);until true;else n(_,g);end else if 4>h then g=r[o];else _=r[s];end end end h=h+1 end t=t+1;e=f[t];end else if h>0 then repeat if 4~=h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;a=e[d];c=n[e[l]];n[a+1]=c;n[a]=c[e[k]];t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end break;end;else local o,c,g,s,r,_,a,h;for h=0,6 do if h<=2 then if 0>=h then n(e[d],e[l]);t=t+1;e=f[t];else if 1~=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];else o=e[d]n[o](n[o+1])t=t+1;e=f[t];end end else if h>4 then if 3~=h then repeat if h<6 then h=0;while h>-1 do if h<=2 then if 1>h then g=e;else if h~=-1 then for e=45,78 do if 2>h then s=d;break;end;r=l;break;end;else r=l;end end else if h>4 then if 1<=h then repeat if 5<h then h=-2;break;end;n(a,_);until true;else n(a,_);end else if 4>h then _=g[r];else a=g[s];end end end h=h+1 end t=t+1;e=f[t];break;end;n[e[d]]={};until true;else h=0;while h>-1 do if h<=2 then if 1>h then g=e;else if h~=-1 then for e=45,78 do if 2>h then s=d;break;end;r=l;break;end;else r=l;end end else if h>4 then if 1<=h then repeat if 5<h then h=-2;break;end;n(a,_);until true;else n(a,_);end else if 4>h then _=g[r];else a=g[s];end end end h=h+1 end t=t+1;e=f[t];end else if h>0 then repeat if 4~=h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;o=e[d];c=n[e[l]];n[o+1]=c;n[o]=c[e[k]];t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end end end else if h<=38 then local e=e[d];o=e+z-1;for t=e,o do local e=c[t-e];n[t]=e;end;else if h~=37 then repeat if h~=40 then n[e[d]]=n[e[l]]%e[k];break;end;local h;h=e[d]n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]();t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];until true;else n[e[d]]=n[e[l]]%e[k];end end end end else if h<29 then if 26>h then if h<24 then n[e[d]]=#n[e[l]];else if 24~=h then n[e[d]]=y(j[e[l]],nil,b);else local h,c,s,a;for g=0,5 do if g>2 then if g>3 then if g>3 then for k=44,73 do if 4<g then t=e[l];break;end;for e=e[d],e[l]do n[e]=nil;end;t=t+1;e=f[t];break;end;else for e=e[d],e[l]do n[e]=nil;end;t=t+1;e=f[t];end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else if g>0 then if 0<g then repeat if 2~=g then h=e[d]n[h]=n[h](r(n,h+1,o))t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];until true;else h=e[d]n[h]=n[h](r(n,h+1,o))t=t+1;e=f[t];end else h=e[d]c,s=_(n[h](r(n,h+1,e[l])))o=s+h-1 a=0;for e=h,o do a=a+1;n[e]=c[a];end;t=t+1;e=f[t];end end end end end else if h>=27 then if h~=26 then for t=23,80 do if h~=27 then n[e[d]]=n[e[l]]-n[e[k]];break;end;local f,r,k,o,b,h;local t=0;while t>-1 do if 3<t then if 6<=t then if t==7 then t=-2;else n[h]=b;end else if t~=4 then h=f[r];else b=o[f[k]];end end else if t<2 then if-4<=t then for n=45,75 do if 0<t then r=d;break;end;f=e;break;end;else f=e;end else if-2<=t then for e=31,58 do if t~=2 then o=n;break;end;k=l;break;end;else k=l;end end end t=t+1 end break;end;else n[e[d]]=n[e[l]]-n[e[k]];end else local d=e[d];local k=n[d+2];local f=n[d]+k;n[d]=f;if(k>0)then if(f<=n[d+1])then t=e[l];n[d+3]=f;end elseif(f>=n[d+1])then t=e[l];n[d+3]=f;end end end else if 32<=h then if h<33 then local o,_,u,s,g,c,h;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];o=e[d]n[o](r(n,o+1,e[l]))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];h=0;while h>-1 do if 3<=h then if 5>h then if 0~=h then for e=25,98 do if 3<h then c=_[u];break;end;g=_[s];break;end;else g=_[s];end else if 4<h then for e=17,98 do if h<6 then n(c,g);break;end;h=-2;break;end;else n(c,g);end end else if h<1 then _=e;else if h>=0 then for e=17,87 do if 2~=h then u=d;break;end;s=l;break;end;else s=l;end end end h=h+1 end t=t+1;e=f[t];o=e[d]n[o](n[o+1])t=t+1;e=f[t];n[e[d]]=a[e[l]];else if h>=32 then repeat if 33<h then local h;h=e[d]n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]();t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];break;end;n[e[d]]=a[e[l]];until true;else n[e[d]]=a[e[l]];end end else if 29<h then if 27<h then repeat if 30~=h then if(n[e[d]]<e[k])then t=t+1;else t=e[l];end;break;end;for e=e[d],e[l]do n[e]=nil;end;until true;else for e=e[d],e[l]do n[e]=nil;end;end else local k,g,o,b,r,h;n[e[d]]=n[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];k=e[d]n[k]=n[k](n[k+1])t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];do return n[e[d]]end t=t+1;e=f[t];k=e[d];g={};for e=1,#s do o=s[e];for e=0,#o do b=o[e];r=b[1];h=b[2];if r==n and h>=k then g[h]=r[h];b[1]=g;end;end;end;t=t+1;e=f[t];t=e[l];end end end end else if 10<h then if 16>=h then if h>=14 then if h<15 then n[e[d]]=n[e[l]][e[k]];else if h==16 then local d=e[d];local k=n[d+2];local f=n[d]+k;n[d]=f;if(k>0)then if(f<=n[d+1])then t=e[l];n[d+3]=f;end elseif(f>=n[d+1])then t=e[l];n[d+3]=f;end else t=e[l];end end else if h>11 then if 8<h then repeat if h<13 then if n[e[d]]then t=t+1;else t=e[l];end;break;end;local h,g;for o=0,6 do if 2<o then if o<5 then if 4==o then n(e[d],e[l]);t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else if o>=3 then repeat if o~=6 then n(e[d],e[l]);t=t+1;e=f[t];break;end;h=e[d]n[h]=n[h](r(n,h+1,e[l]))until true;else n(e[d],e[l]);t=t+1;e=f[t];end end else if o<1 then n[e[d]]=a[e[l]];t=t+1;e=f[t];else if-3~=o then for r=15,53 do if o>1 then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];break;end;else h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];end end end end until true;else local h,g;for o=0,6 do if 2<o then if o<5 then if 4==o then n(e[d],e[l]);t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else if o>=3 then repeat if o~=6 then n(e[d],e[l]);t=t+1;e=f[t];break;end;h=e[d]n[h]=n[h](r(n,h+1,e[l]))until true;else n(e[d],e[l]);t=t+1;e=f[t];end end else if o<1 then n[e[d]]=a[e[l]];t=t+1;e=f[t];else if-3~=o then for r=15,53 do if o>1 then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];break;end;else h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];end end end end end else local h,r;for o=0,6 do if 2<o then if 4>=o then if 0~=o then repeat if 3<o then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else if 5~=o then h=e[d];r=n[e[l]];n[h+1]=r;n[h]=r[e[k]];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end else if 1<=o then if o==2 then n[e[d]]=b[e[l]];t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else h=e[d]n[h]=n[h](n[h+1])t=t+1;e=f[t];end end end end end else if h<20 then if h<18 then local _,c,s,g,o,a,h,b;for h=0,4 do if h>=2 then if h<=2 then n(e[d],e[l]);t=t+1;e=f[t];else if h>3 then if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;else b=e[d]n[b]=n[b](r(n,b+1,e[l]))t=t+1;e=f[t];end end else if h>-1 then for k=18,77 do if h>0 then n(e[d],e[l]);t=t+1;e=f[t];break;end;h=0;while h>-1 do if h>=4 then if 5>=h then if 5~=h then o=g[_[s]];else a=_[c];end else if 5~=h then repeat if 7>h then n[a]=o;break;end;h=-2;until true;else n[a]=o;end end else if h>1 then if h>1 then for e=23,69 do if h>2 then g=n;break;end;s=l;break;end;else g=n;end else if 0~=h then c=d;else _=e;end end end h=h+1 end t=t+1;e=f[t];break;end;else n(e[d],e[l]);t=t+1;e=f[t];end end end else if 16<h then for f=41,82 do if 19~=h then local t=e[d]local d,e=_(n[t](r(n,t+1,e[l])))o=e+t-1 local e=0;for t=t,o do e=e+1;n[t]=d[e];end;break;end;if(e[d]<n[e[k]])then t=e[l];else t=t+1;end;break;end;else if(e[d]<n[e[k]])then t=e[l];else t=t+1;end;end end else if 20>=h then n[e[d]][n[e[l]]]=n[e[k]];else if h>=20 then for k=49,90 do if h>21 then local k,a,g,h;for r=0,6 do if r>=3 then if r<5 then if r~=3 then n[e[d]]=b[e[l]];t=t+1;e=f[t];else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if 2~=r then repeat if r>5 then k=e[d]a,g=_(n[k](n[k+1]))o=g+k-1 h=0;for e=k,o do h=h+1;n[e]=a[h];end;break;end;n(e[d],e[l]);t=t+1;e=f[t];until true;else k=e[d]a,g=_(n[k](n[k+1]))o=g+k-1 h=0;for e=k,o do h=h+1;n[e]=a[h];end;end end else if 1<=r then if-3<r then for h=46,56 do if r~=2 then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;k=e[d]n[k]=n[k]()t=t+1;e=f[t];break;end;else k=e[d]n[k]=n[k]()t=t+1;e=f[t];end else b[e[l]]=n[e[d]];t=t+1;e=f[t];end end end break;end;local e=e[d]n[e]=n[e](n[e+1])break;end;else local k,a,g,r;for h=0,6 do if h>=3 then if h<5 then if h~=3 then n[e[d]]=b[e[l]];t=t+1;e=f[t];else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if 2~=h then repeat if h>5 then k=e[d]a,g=_(n[k](n[k+1]))o=g+k-1 r=0;for e=k,o do r=r+1;n[e]=a[r];end;break;end;n(e[d],e[l]);t=t+1;e=f[t];until true;else k=e[d]a,g=_(n[k](n[k+1]))o=g+k-1 r=0;for e=k,o do r=r+1;n[e]=a[r];end;end end else if 1<=h then if-3<h then for o=46,56 do if h~=2 then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;k=e[d]n[k]=n[k]()t=t+1;e=f[t];break;end;else k=e[d]n[k]=n[k]()t=t+1;e=f[t];end else b[e[l]]=n[e[d]];t=t+1;e=f[t];end end end end end end end else if 4>=h then if 1>=h then if-2<=h then repeat if 1>h then local b,_,g,a,s,c,o,h;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];b=e[d];_=n[e[l]];n[b+1]=_;n[b]=_[e[k]];t=t+1;e=f[t];h=0;while h>-1 do if h>=3 then if h<=4 then if h>2 then repeat if h>3 then o=g[a];break;end;c=g[s];until true;else o=g[a];end else if h>1 then for e=21,98 do if 6~=h then n(o,c);break;end;h=-2;break;end;else n(o,c);end end else if h>0 then if h>-3 then repeat if h>1 then s=l;break;end;a=d;until true;else s=l;end else g=e;end end h=h+1 end t=t+1;e=f[t];n[e[d]]={};t=t+1;e=f[t];n[e[d]][e[l]]=e[k];t=t+1;e=f[t];n[e[d]][e[l]]=e[k];t=t+1;e=f[t];b=e[d]n[b](r(n,b+1,e[l]))break;end;local k,a,s,h;for g=0,6 do if g<3 then if g<1 then n(e[d],e[l]);t=t+1;e=f[t];else if g~=-3 then for k=45,65 do if 2>g then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end else if 4>=g then if 1<=g then for l=36,73 do if g<4 then k=e[d]a,s=_(n[k]())o=s+k-1 h=0;for e=k,o do h=h+1;n[e]=a[h];end;t=t+1;e=f[t];break;end;k=e[d]a,s=_(n[k](r(n,k+1,o)))o=s+k-1 h=0;for e=k,o do h=h+1;n[e]=a[h];end;t=t+1;e=f[t];break;end;else k=e[d]a,s=_(n[k](r(n,k+1,o)))o=s+k-1 h=0;for e=k,o do h=h+1;n[e]=a[h];end;t=t+1;e=f[t];end else if 3<=g then for h=20,85 do if 6~=g then k=e[d]n[k](r(n,k+1,o))t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];break;end;else k=e[d]n[k](r(n,k+1,o))t=t+1;e=f[t];end end end end until true;else local b,c,g,a,_,s,o,h;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];b=e[d];c=n[e[l]];n[b+1]=c;n[b]=c[e[k]];t=t+1;e=f[t];h=0;while h>-1 do if h>=3 then if h<=4 then if h>2 then repeat if h>3 then o=g[a];break;end;s=g[_];until true;else o=g[a];end else if h>1 then for e=21,98 do if 6~=h then n(o,s);break;end;h=-2;break;end;else n(o,s);end end else if h>0 then if h>-3 then repeat if h>1 then _=l;break;end;a=d;until true;else _=l;end else g=e;end end h=h+1 end t=t+1;e=f[t];n[e[d]]={};t=t+1;e=f[t];n[e[d]][e[l]]=e[k];t=t+1;e=f[t];n[e[d]][e[l]]=e[k];t=t+1;e=f[t];b=e[d]n[b](r(n,b+1,e[l]))end else if h>=3 then if-1<h then for t=24,55 do if h~=3 then local e=e[d]n[e]=n[e]()break;end;n(e[d],e[l]);break;end;else local e=e[d]n[e]=n[e]()end else local g,h,_,o,r,b,a,s,c;local f=0;while f>-1 do if f<=2 then if 1<=f then if-2<=f then for n=13,66 do if f>1 then o=h[d];r=h[k];b=l;break;end;h=e;_=t;break;end;else o=h[d];r=h[k];b=l;end else g=n;end else if f<5 then if 4==f then c=a==s and h[b]or 1+_;else a=g[o];s=g[r];end else if 6>f then t=c;else f=-2;end end end f=f+1 end end end else if h<=7 then if h>=6 then if h~=3 then repeat if h~=7 then local h,a,c,s,g;n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];h=e[d];a=n[e[l]];n[h+1]=a;n[h]=a[e[k]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]c,s=_(n[h](r(n,h+1,e[l])))o=s+h-1 g=0;for e=h,o do g=g+1;n[e]=c[g];end;t=t+1;e=f[t];h=e[d]n[h]=n[h](r(n,h+1,o))t=t+1;e=f[t];n[e[d]]();break;end;do return n[e[d]]end until true;else do return n[e[d]]end end else local b;for h=0,6 do if 2<h then if 4>=h then if h>0 then repeat if h>3 then b=e[d]n[b]=n[b](r(n,b+1,e[l]))t=t+1;e=f[t];break;end;n(e[d],e[l]);t=t+1;e=f[t];until true;else n(e[d],e[l]);t=t+1;e=f[t];end else if 5<h then t=e[l];else n[e[d]][e[l]]=n[e[k]];t=t+1;e=f[t];end end else if h>0 then if-2~=h then repeat if h~=2 then n(e[d],e[l]);t=t+1;e=f[t];break;end;n(e[d],e[l]);t=t+1;e=f[t];until true;else n(e[d],e[l]);t=t+1;e=f[t];end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end else if 8>=h then n[e[d]]=#n[e[l]];else if 8<=h then for g=10,58 do if h<10 then local g,y,u,z,ee,p,c,h,m,j,s;n[e[d]]=a[e[l]];t=t+1;e=f[t];g=e[d];y=n[e[l]];n[g+1]=y;n[g]=y[e[k]];t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];h=0;while h>-1 do if 2<h then if 5<=h then if h>3 then for e=46,77 do if 5<h then h=-2;break;end;n(c,p);break;end;else n(c,p);end else if-1<h then for e=44,82 do if 3~=h then c=u[z];break;end;p=u[ee];break;end;else c=u[z];end end else if 0>=h then u=e;else if h==2 then ee=l;else z=d;end end end h=h+1 end t=t+1;e=f[t];g=e[d]m,j=_(n[g](n[g+1]))o=j+g-1 s=0;for e=g,o do s=s+1;n[e]=m[s];end;t=t+1;e=f[t];g=e[d]n[g]=n[g](r(n,g+1,o))t=t+1;e=f[t];n[e[d]]=b[e[l]];break;end;n(e[d],e[l]);break;end;else n(e[d],e[l]);end end end end end end end else if h<=140 then if 117>h then if h>=105 then if h<111 then if h<=107 then if 106<=h then if 104<=h then repeat if 107>h then local d=e[d];local f=n[d]local k=n[d+2];if(k>0)then if(f>n[d+1])then t=e[l];else n[d+3]=f;end elseif(f<n[d+1])then t=e[l];else n[d+3]=f;end break;end;local e=e[d];local t=n[e];for e=e+1,o do g.oxrwXhFS(t,n[e])end;until true;else local e=e[d];local t=n[e];for e=e+1,o do g.oxrwXhFS(t,n[e])end;end else local h;h=e[d]n[h](n[h+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h](n[h+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];end else if h<=108 then local d=e[d]local l={n[d](n[d+1])};local t=0;for e=d,e[k]do t=t+1;n[e]=l[t];end else if 108<=h then repeat if h>109 then local e=e[d]local d,t=_(n[e]())o=t+e-1 local t=0;for e=e,o do t=t+1;n[e]=d[t];end;break;end;local k,a,s,g;for h=0,6 do if h>=3 then if 4>=h then if h~=-1 then repeat if h>3 then n(e[d],e[l]);t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];until true;else n(e[d],e[l]);t=t+1;e=f[t];end else if 4~=h then repeat if 6>h then n(e[d],e[l]);t=t+1;e=f[t];break;end;k=e[d]n[k](r(n,k+1,e[l]))until true;else k=e[d]n[k](r(n,k+1,e[l]))end end else if h<=0 then n(e[d],e[l]);t=t+1;e=f[t];else if 2~=h then k=e[d]a,s=_(n[k](n[k+1]))o=s+k-1 g=0;for e=k,o do g=g+1;n[e]=a[g];end;t=t+1;e=f[t];else k=e[d]n[k](r(n,k+1,o))t=t+1;e=f[t];end end end end until true;else local k,s,a,g;for h=0,6 do if h>=3 then if 4>=h then if h~=-1 then repeat if h>3 then n(e[d],e[l]);t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];until true;else n(e[d],e[l]);t=t+1;e=f[t];end else if 4~=h then repeat if 6>h then n(e[d],e[l]);t=t+1;e=f[t];break;end;k=e[d]n[k](r(n,k+1,e[l]))until true;else k=e[d]n[k](r(n,k+1,e[l]))end end else if h<=0 then n(e[d],e[l]);t=t+1;e=f[t];else if 2~=h then k=e[d]s,a=_(n[k](n[k+1]))o=a+k-1 g=0;for e=k,o do g=g+1;n[e]=s[g];end;t=t+1;e=f[t];else k=e[d]n[k](r(n,k+1,o))t=t+1;e=f[t];end end end end end end end else if h<114 then if 112>h then n[e[d]][e[l]]=e[k];else if h>=108 then for t=48,80 do if 112~=h then n[e[d]]=n[e[l]]+n[e[k]];break;end;local e=e[d];local t=n[e];for e=e+1,o do g.oxrwXhFS(t,n[e])end;break;end;else n[e[d]]=n[e[l]]+n[e[k]];end end else if 115>h then local h,b;h=e[d];b=n[e[l]];n[h+1]=b;n[h]=b[e[k]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];h=e[d];b=n[e[l]];n[h+1]=b;n[h]=b[e[k]];else if 114<=h then repeat if h~=116 then n[e[d]]();break;end;local h;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h](r(n,h+1,e[l]))t=t+1;e=f[t];t=e[l];until true;else local h;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h](r(n,h+1,e[l]))t=t+1;e=f[t];t=e[l];end end end end else if 98>=h then if h<96 then if 92~=h then for o=10,73 do if 94~=h then local h,o;h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];h=e[d];o=n[e[l]];n[h+1]=o;n[h]=o[e[k]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];break;end;local t=e[d]n[t](r(n,t+1,e[l]))break;end;else local h,o;h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];h=e[d];o=n[e[l]];n[h+1]=o;n[h]=o[e[k]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];end else if h>96 then if 97==h then local b;for h=0,4 do if 2<=h then if h>2 then if h~=2 then repeat if 4>h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;if(n[e[d]]<n[e[k]])then t=e[l];else t=t+1;end;until true;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else n[e[d]]=n[e[l]]-n[e[k]];t=t+1;e=f[t];end else if-3~=h then repeat if h>0 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;b=e[d]n[b]=n[b](n[b+1])t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end else local d=e[d];local t=n[e[l]];n[d+1]=t;n[d]=t[e[k]];end else local l=e[l];local t=n[l]for e=l+1,e[k]do t=t..n[e];end;n[e[d]]=t;end end else if 102>h then if h>=100 then if h>96 then repeat if 100<h then local g,c,a,p,z,u,s,h,m,j,y;for h=0,6 do if h<=2 then if 1<=h then if h~=-2 then repeat if h>1 then g=e[d]n[g]=n[g](r(n,g+1,e[l]))t=t+1;e=f[t];break;end;h=0;while h>-1 do if 3>h then if 1<=h then if 2==h then z=l;else p=d;end else a=e;end else if 5>h then if h~=3 then s=a[p];else u=a[z];end else if h~=3 then for e=17,84 do if h~=6 then n(s,u);break;end;h=-2;break;end;else n(s,u);end end end h=h+1 end t=t+1;e=f[t];until true;else h=0;while h>-1 do if 3>h then if 1<=h then if 2==h then z=l;else p=d;end else a=e;end else if 5>h then if h~=3 then s=a[p];else u=a[z];end else if h~=3 then for e=17,84 do if h~=6 then n(s,u);break;end;h=-2;break;end;else n(s,u);end end end h=h+1 end t=t+1;e=f[t];end else g=e[d];c=n[e[l]];n[g+1]=c;n[g]=c[e[k]];t=t+1;e=f[t];end else if 5<=h then if h>5 then g=e[d]m,j=_(n[g](n[g+1]))o=j+g-1 y=0;for e=g,o do y=y+1;n[e]=m[y];end;else h=0;while h>-1 do if h>=3 then if h<5 then if h>=-1 then repeat if 4~=h then u=a[z];break;end;s=a[p];until true;else s=a[p];end else if 4<h then for e=12,66 do if 6>h then n(s,u);break;end;h=-2;break;end;else h=-2;end end else if 1<=h then if 1~=h then z=l;else p=d;end else a=e;end end h=h+1 end t=t+1;e=f[t];end else if 1<h then for o=46,95 do if h~=3 then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;g=e[d];c=n[e[l]];n[g+1]=c;n[g]=c[e[k]];t=t+1;e=f[t];break;end;else g=e[d];c=n[e[l]];n[g+1]=c;n[g]=c[e[k]];t=t+1;e=f[t];end end end end break;end;local h,b;for o=0,2 do if o>=1 then if o<2 then h=e[d];b=n[e[l]];n[h+1]=b;n[h]=b[e[k]];t=t+1;e=f[t];else h=e[d]n[h](n[h+1])end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end until true;else local h,b;for o=0,2 do if o>=1 then if o<2 then h=e[d];b=n[e[l]];n[h+1]=b;n[h]=b[e[k]];t=t+1;e=f[t];else h=e[d]n[h](n[h+1])end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end else local h,o;for b=0,5 do if b>2 then if 4<=b then if 1<=b then repeat if 5>b then n[e[d]]=(e[l]~=0);t=t+1;e=f[t];break;end;h=e[d]n[h](r(n,h+1,e[l]))until true;else h=e[d]n[h](r(n,h+1,e[l]))end else h=e[d];o=n[e[l]];n[h+1]=o;n[h]=o[e[k]];t=t+1;e=f[t];end else if b>=1 then if b==1 then n(e[d],e[l]);t=t+1;e=f[t];else h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];end else h=e[d];o=n[e[l]];n[h+1]=o;n[h]=o[e[k]];t=t+1;e=f[t];end end end end else if 102<h then if 104==h then do return end;else local t=e[d]n[t](r(n,t+1,e[l]))end else local e=e[d]n[e](n[e+1])end end end end else if 129<=h then if 134<h then if h>137 then if h<139 then n[e[d]]=n[e[l]]-n[e[k]];else if h>139 then local e=e[d]n[e]=n[e](r(n,e+1,o))else local h;for b=0,2 do if b>0 then if 0<b then repeat if 2~=b then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;until true;else if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;end else h=e[d]n[h]=n[h]()t=t+1;e=f[t];end end end end else if h<=135 then local t=e[d]local l={n[t](n[t+1])};local d=0;for e=t,e[k]do d=d+1;n[e]=l[d];end else if h>=134 then for o=11,91 do if h~=136 then for h=0,6 do if 3>h then if 0>=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];else if h>=-2 then for o=31,95 do if 1<h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end else if 5>h then if 3~=h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else if 6>h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]];end end end end break;end;if not n[e[d]]then t=t+1;else t=e[l];end;break;end;else for h=0,6 do if 3>h then if 0>=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];else if h>=-2 then for o=31,95 do if 1<h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end else if 5>h then if 3~=h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else if 6>h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]];end end end end end end end else if h<=131 then if h<130 then local k;n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];k=e[d]n[k](n[k+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]();t=t+1;e=f[t];do return end;else if 131~=h then n[e[d]]();else n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];n(e[d],e[l]);end end else if h>132 then if h>=130 then repeat if 134>h then local e=e[d]local d,t=_(n[e](n[e+1]))o=t+e-1 local t=0;for e=e,o do t=t+1;n[e]=d[t];end;break;end;n[e[d]][e[l]]=e[k];until true;else n[e[d]][e[l]]=e[k];end else if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;end end end else if 122<h then if 126>h then if 123>=h then local g,c,s,b,_,r,o,h;for h=0,4 do if 2>h then if h>-2 then for b=21,56 do if 0~=h then n[e[d]]=n[e[l]]+n[e[k]];t=t+1;e=f[t];break;end;n[e[d]]=a[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=n[e[l]]+n[e[k]];t=t+1;e=f[t];end else if 2<h then if 0<h then for a=13,88 do if h~=3 then h=0;while h>-1 do if 3>h then if 0<h then if 0~=h then for t=45,52 do if h~=1 then _=b[c];break;end;b=e;break;end;else b=e;end else g=d;c=l;s=k;end else if h<=4 then if 1~=h then for e=11,75 do if h<4 then r=b[g];break;end;o=n[_];for e=1+_,b[s]do o=o..n[e];end;break;end;else r=b[g];end else if h>3 then repeat if 5~=h then h=-2;break;end;n[r]=o;until true;else n[r]=o;end end end h=h+1 end break;end;n[e[d]]=n[e[l]][n[e[k]]];t=t+1;e=f[t];break;end;else h=0;while h>-1 do if 3>h then if 0<h then if 0~=h then for t=45,52 do if h~=1 then _=b[c];break;end;b=e;break;end;else b=e;end else g=d;c=l;s=k;end else if h<=4 then if 1~=h then for e=11,75 do if h<4 then r=b[g];break;end;o=n[_];for e=1+_,b[s]do o=o..n[e];end;break;end;else r=b[g];end else if h>3 then repeat if 5~=h then h=-2;break;end;n[r]=o;until true;else n[r]=o;end end end h=h+1 end end else n[e[d]]=n[e[l]]%e[k];t=t+1;e=f[t];end end end else if h~=122 then for t=38,58 do if h~=125 then a[e[l]]=n[e[d]];break;end;n[e[d]]=b[e[l]];break;end;else a[e[l]]=n[e[d]];end end else if h<127 then local t=e[d]n[t]=n[t](r(n,t+1,e[l]))else if 124~=h then repeat if h~=127 then local h,g;for o=0,6 do if 2>=o then if 0>=o then h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];else if 0<=o then repeat if 2~=o then n(e[d],e[l]);t=t+1;e=f[t];break;end;h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];until true;else h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];end end else if o>4 then if 5<o then n[e[d]]=b[e[l]];else h=e[d]n[h](n[h+1])t=t+1;e=f[t];end else if o==4 then h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end break;end;local b,o,g,_,a,s,c,h;for h=0,6 do if h>2 then if h<5 then if 2<h then for r=48,98 do if h~=4 then b=e[d];o=n[e[l]];n[b+1]=o;n[b]=o[e[k]];t=t+1;e=f[t];break;end;n[e[d]]=(e[l]~=0);t=t+1;e=f[t];break;end;else n[e[d]]=(e[l]~=0);t=t+1;e=f[t];end else if 6==h then t=e[l];else b=e[d]n[b](r(n,b+1,e[l]))t=t+1;e=f[t];end end else if 0>=h then b=e[d];o=n[e[l]];n[b+1]=o;n[b]=o[e[k]];t=t+1;e=f[t];else if-3<=h then repeat if 1<h then b=e[d]n[b]=n[b](r(n,b+1,e[l]))t=t+1;e=f[t];break;end;h=0;while h>-1 do if h<=2 then if 1<=h then if h<2 then _=d;else a=l;end else g=e;end else if 5<=h then if h>=2 then for e=34,85 do if h~=5 then h=-2;break;end;n(c,s);break;end;else h=-2;end else if h~=3 then c=g[_];else s=g[a];end end end h=h+1 end t=t+1;e=f[t];until true;else h=0;while h>-1 do if h<=2 then if 1<=h then if h<2 then _=d;else a=l;end else g=e;end else if 5<=h then if h>=2 then for e=34,85 do if h~=5 then h=-2;break;end;n(c,s);break;end;else h=-2;end else if h~=3 then c=g[_];else s=g[a];end end end h=h+1 end t=t+1;e=f[t];end end end end until true;else local h,g;for o=0,6 do if 2>=o then if 0>=o then h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];else if 0<=o then repeat if 2~=o then n(e[d],e[l]);t=t+1;e=f[t];break;end;h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];until true;else h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];end end else if o>4 then if 5<o then n[e[d]]=b[e[l]];else h=e[d]n[h](n[h+1])t=t+1;e=f[t];end else if o==4 then h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end end end end else if h>=120 then if 120>=h then local k;for h=0,4 do if h>1 then if 3>h then n(e[d],e[l]);t=t+1;e=f[t];else if h>=1 then for b=28,70 do if h<4 then k=e[d]n[k]=n[k](n[k+1])t=t+1;e=f[t];break;end;if n[e[d]]then t=t+1;else t=e[l];end;break;end;else if n[e[d]]then t=t+1;else t=e[l];end;end end else if 0<h then n[e[d]]=b[e[l]];t=t+1;e=f[t];else k=e[d]n[k](r(n,k+1,e[l]))t=t+1;e=f[t];end end end else if h>=117 then for o=10,76 do if h<122 then do return end;break;end;local h;for o=0,4 do if o>=2 then if 3<=o then if 4>o then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else if(n[e[d]]~=e[k])then t=t+1;else t=e[l];end;end else h=e[d]n[h]=n[h]()t=t+1;e=f[t];end else if o>=-1 then for k=41,91 do if 1~=o then h=e[d]n[h](n[h+1])t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end end break;end;else local h;for o=0,4 do if o>=2 then if 3<=o then if 4>o then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else if(n[e[d]]~=e[k])then t=t+1;else t=e[l];end;end else h=e[d]n[h]=n[h]()t=t+1;e=f[t];end else if o>=-1 then for k=41,91 do if 1~=o then h=e[d]n[h](n[h+1])t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end end end end else if h>117 then if h>115 then for g=41,57 do if 119~=h then if(e[d]<n[e[k]])then t=e[l];else t=t+1;end;break;end;local h,u,s,c,g;for a=0,4 do if 1<a then if a>2 then if 0<a then for l=48,53 do if 4>a then h=e[d]s,c=_(n[h](n[h+1]))o=c+h-1 g=0;for e=h,o do g=g+1;n[e]=s[g];end;t=t+1;e=f[t];break;end;h=e[d]n[h]=n[h](r(n,h+1,o))break;end;else h=e[d]s,c=_(n[h](n[h+1]))o=c+h-1 g=0;for e=h,o do g=g+1;n[e]=s[g];end;t=t+1;e=f[t];end else n(e[d],e[l]);t=t+1;e=f[t];end else if 0~=a then n[e[d]]=b[e[l]];t=t+1;e=f[t];else h=e[d];u=n[e[l]];n[h+1]=u;n[h]=u[e[k]];t=t+1;e=f[t];end end end break;end;else if(e[d]<n[e[k]])then t=e[l];else t=t+1;end;end else if(n[e[d]]<e[k])then t=t+1;else t=e[l];end;end end end end end else if 164>h then if h<=151 then if h<146 then if h<=142 then if 140<=h then repeat if h~=142 then local h,o;n[e[d]]();t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];h=e[d];o=n[e[l]];n[h+1]=o;n[h]=o[e[k]];t=t+1;e=f[t];n(e[d],e[l]);break;end;local k,a,g,h;n(e[d],e[l]);t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];k=e[d]a,g=_(n[k](n[k+1]))o=g+k-1 h=0;for e=k,o do h=h+1;n[e]=a[h];end;t=t+1;e=f[t];k=e[d]n[k](r(n,k+1,o))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);until true;else local k,a,g,h;n(e[d],e[l]);t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];k=e[d]a,g=_(n[k](n[k+1]))o=g+k-1 h=0;for e=k,o do h=h+1;n[e]=a[h];end;t=t+1;e=f[t];k=e[d]n[k](r(n,k+1,o))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);end else if 143<h then if 141<h then repeat if 144<h then local k;n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];k=e[d]n[k](n[k+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]();t=t+1;e=f[t];do return end;break;end;local h;n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];h=e[d]n[h](r(n,h+1,e[l]))t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];h=e[d]n[h](n[h+1])until true;else local k;n[e[d]]=b[e[l]];t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];k=e[d]n[k](n[k+1])t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]();t=t+1;e=f[t];do return end;end else local f=e[d];local l={};for e=1,#s do local e=s[e];for t=0,#e do local t=e[t];local d=t[1];local e=t[2];if d==n and e>=f then l[e]=d[e];t[1]=l;end;end;end;end end else if h>=149 then if h>149 then if 148<=h then repeat if h<151 then local o;for h=0,6 do if h>=3 then if 5>h then if h>2 then for k=36,61 do if 3~=h then o=e[d]n[o](r(n,o+1,e[l]))t=t+1;e=f[t];break;end;n(e[d],e[l]);t=t+1;e=f[t];break;end;else n(e[d],e[l]);t=t+1;e=f[t];end else if h>4 then for k=21,80 do if 5<h then n[e[d]]();break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end else if h<1 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else if-3~=h then repeat if 2>h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]];t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]];t=t+1;e=f[t];end end end end break;end;local t=e[d]local l={n[t](r(n,t+1,o))};local d=0;for e=t,e[k]do d=d+1;n[e]=l[d];end until true;else local o;for h=0,6 do if h>=3 then if 5>h then if h>2 then for k=36,61 do if 3~=h then o=e[d]n[o](r(n,o+1,e[l]))t=t+1;e=f[t];break;end;n(e[d],e[l]);t=t+1;e=f[t];break;end;else n(e[d],e[l]);t=t+1;e=f[t];end else if h>4 then for k=21,80 do if 5<h then n[e[d]]();break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end else if h<1 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else if-3~=h then repeat if 2>h then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]];t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]];t=t+1;e=f[t];end end end end end else local h,g,s,c,b;n[e[d]]=a[e[l]];t=t+1;e=f[t];h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];h=e[d]s,c=_(n[h](r(n,h+1,e[l])))o=c+h-1 b=0;for e=h,o do b=b+1;n[e]=s[b];end;t=t+1;e=f[t];h=e[d]n[h](r(n,h+1,o))t=t+1;e=f[t];do return end;end else if h<=146 then if(n[e[d]]~=e[k])then t=t+1;else t=e[l];end;else if 143~=h then for f=36,70 do if h>147 then b[e[l]]=n[e[d]];break;end;local f=n[e[k]];if not f then t=t+1;else n[e[d]]=f;t=e[l];end;break;end;else b[e[l]]=n[e[d]];end end end end else if 157>=h then if h>154 then if h>155 then if 152<=h then for t=37,83 do if 157>h then local t=e[d]local d,e=_(n[t]())o=e+t-1 local e=0;for t=t,o do e=e+1;n[t]=d[e];end;break;end;n[e[d]]=(e[l]~=0);break;end;else n[e[d]]=(e[l]~=0);end else local o,r,g,a,s,c,_,h;for h=0,6 do if h<=2 then if 0<h then if h==1 then n[e[d]]=b[e[l]];t=t+1;e=f[t];else o=e[d];r=n[e[l]];n[o+1]=r;n[o]=r[e[k]];t=t+1;e=f[t];end else o=e[d];r=n[e[l]];n[o+1]=r;n[o]=r[e[k]];t=t+1;e=f[t];end else if h<5 then if 4>h then n(e[d],e[l]);t=t+1;e=f[t];else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else if h==6 then h=0;while h>-1 do if h<3 then if 0>=h then g=e;else if h==1 then a=d;else s=l;end end else if 5<=h then if 5==h then n(_,c);else h=-2;end else if 0<h then repeat if 3~=h then _=g[a];break;end;c=g[s];until true;else _=g[a];end end end h=h+1 end else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end end end end end else if h>=153 then if 149~=h then repeat if 153~=h then if(e[d]<n[e[k]])then t=t+1;else t=e[l];end;break;end;if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;until true;else if(n[e[d]]==e[k])then t=t+1;else t=e[l];end;end else local o,c,a,g,u,s,_,h;n(e[d],e[l]);t=t+1;e=f[t];o=e[d];c=n[e[l]];n[o+1]=c;n[o]=c[e[k]];t=t+1;e=f[t];h=0;while h>-1 do if 3<=h then if h>4 then if 3<=h then repeat if h~=5 then h=-2;break;end;n(_,s);until true;else n(_,s);end else if h~=-1 then for e=11,69 do if h~=3 then _=a[g];break;end;s=a[u];break;end;else _=a[g];end end else if h<=0 then a=e;else if-3<=h then repeat if 2~=h then g=d;break;end;u=l;until true;else g=d;end end end h=h+1 end t=t+1;e=f[t];o=e[d]n[o]=n[o](r(n,o+1,e[l]))t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];n(e[d],e[l]);t=t+1;e=f[t];n[e[d]]=b[e[l]];end end else if h<161 then if h>=159 then if h~=160 then n[e[d]]=b[e[l]];else local h,g;for o=0,6 do if o<=2 then if o>=1 then if o>=-2 then repeat if 1<o then h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];t=t+1;e=f[t];break;end;n[e[d]]=b[e[l]];t=t+1;e=f[t];until true;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end else h=e[d]n[h](n[h+1])t=t+1;e=f[t];end else if 4>=o then if o>=1 then repeat if 3<o then h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];break;end;n(e[d],e[l]);t=t+1;e=f[t];until true;else n(e[d],e[l]);t=t+1;e=f[t];end else if o~=2 then repeat if o~=6 then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;h=e[d];g=n[e[l]];n[h+1]=g;n[h]=g[e[k]];until true;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end end end end else local r=j[e[l]];local o;local h={};o=g.JHsvdHTe({},{__index=function(t,e)local e=h[e];return e[1][e[2]];end,__newindex=function(n,e,t)local e=h[e]e[1][e[2]]=t;end;});for d=1,e[k]do t=t+1;local e=f[t];if e[le]==69 then h[d-1]={n,e[l]};else h[d-1]={a,e[l]};end;s[#s+1]=h;end;n[e[d]]=y(r,o,b);end else if h<162 then if(n[e[d]]<n[e[k]])then t=e[l];else t=t+1;end;else if h>161 then for f=34,85 do if h<163 then if(n[e[d]]<n[e[k]])then t=e[l];else t=t+1;end;break;end;n[e[d]]=n[e[l]][e[k]];break;end;else if(n[e[d]]<n[e[k]])then t=e[l];else t=t+1;end;end end end end end else if h<176 then if 169<h then if 173<=h then if 174<=h then if 173<=h then for f=25,88 do if 174~=h then local e=e[d]local d,t=_(n[e](n[e+1]))o=t+e-1 local t=0;for e=e,o do t=t+1;n[e]=d[t];end;break;end;if(n[e[d]]~=e[k])then t=t+1;else t=e[l];end;break;end;else if(n[e[d]]~=e[k])then t=t+1;else t=e[l];end;end else n[e[d]]=n[e[l]]+n[e[k]];end else if h>170 then if h>=169 then repeat if h<172 then local o,_,r,g,a,h;n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];h=0;while h>-1 do if 3<=h then if h>4 then if 4<h then for e=15,63 do if 5~=h then h=-2;break;end;n(a,g);break;end;else h=-2;end else if-1<h then for e=35,66 do if h<4 then g=o[r];break;end;a=o[_];break;end;else g=o[r];end end else if 1<=h then if 2==h then r=l;else _=d;end else o=e;end end h=h+1 end break;end;local h,b;for o=0,3 do if 2<=o then if o>2 then if not n[e[d]]then t=t+1;else t=e[l];end;else h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];end else if o>-4 then for r=33,66 do if o<1 then h=e[d];b=n[e[l]];n[h+1]=b;n[h]=b[e[k]];t=t+1;e=f[t];break;end;n(e[d],e[l]);t=t+1;e=f[t];break;end;else h=e[d];b=n[e[l]];n[h+1]=b;n[h]=b[e[k]];t=t+1;e=f[t];end end end until true;else local o,a,g,r,_,h;n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=n[e[l]];t=t+1;e=f[t];h=0;while h>-1 do if 3<=h then if h>4 then if 4<h then for e=15,63 do if 5~=h then h=-2;break;end;n(_,r);break;end;else h=-2;end else if-1<h then for e=35,66 do if h<4 then r=o[g];break;end;_=o[a];break;end;else r=o[g];end end else if 1<=h then if 2==h then g=l;else a=d;end else o=e;end end h=h+1 end end else local e=e[d]local d,t=_(n[e](r(n,e+1,o)))o=t+e-1 local t=0;for e=e,o do t=t+1;n[e]=d[t];end;end end else if 166>=h then if h>=165 then if 166==h then local o;for h=0,6 do if h>=3 then if h<5 then if 2<h then for k=44,67 do if h~=3 then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;o=e[d]n[o](r(n,o+1,e[l]))t=t+1;e=f[t];break;end;else o=e[d]n[o](r(n,o+1,e[l]))t=t+1;e=f[t];end else if h>=1 then repeat if 6~=h then n[e[d]]=b[e[l]];t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]][e[k]];until true;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end else if h<1 then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];else if h>0 then repeat if 1<h then n(e[d],e[l]);t=t+1;e=f[t];break;end;n[e[d]]=n[e[l]];t=t+1;e=f[t];until true;else n(e[d],e[l]);t=t+1;e=f[t];end end end end else n[e[d]]=n[e[l]]+e[k];end else n[e[d]][n[e[l]]]=n[e[k]];end else if h<168 then n[e[d]]=n[e[l]][n[e[k]]];else if 168==h then for k=0,1 do if 1==k then if not n[e[d]]then t=t+1;else t=e[l];end;else n[e[d]]=b[e[l]];t=t+1;e=f[t];end end else local d=e[d];local k=e[k];local f=d+2 local d={n[d](n[d+1],n[f])};for e=1,k do n[f+e]=d[e];end;local d=d[1]if d then n[f]=d t=e[l];else t=t+1;end;end end end end else if 181<h then if h<185 then if 183<=h then if 184~=h then local t=e[d];local d=n[e[l]];n[t+1]=d;n[t]=d[e[k]];else local h;n[e[d]]=b[e[l]];t=t+1;e=f[t];h=e[d]n[h]=n[h]()t=t+1;e=f[t];for e=e[d],e[l]do n[e]=nil;end;t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];n[e[d]]=b[e[l]];t=t+1;e=f[t];n[e[d]]=b[e[l]];end else local t=e[d]local d,e=_(n[t](r(n,t+1,e[l])))o=e+t-1 local e=0;for t=t,o do e=e+1;n[t]=d[e];end;end else if h<=185 then do return n[e[d]]end else if h==187 then if n[e[d]]then t=t+1;else t=e[l];end;else n[e[d]][e[l]]=n[e[k]];end end end else if h>=179 then if h>179 then if 177~=h then repeat if 181~=h then local t=e[d]n[t]=n[t](r(n,t+1,e[l]))break;end;b[e[l]]=n[e[d]];until true;else b[e[l]]=n[e[d]];end else if not n[e[d]]then t=t+1;else t=e[l];end;end else if h<=176 then local d=e[d];local k=e[k];local f=d+2 local d={n[d](n[d+1],n[f])};for e=1,k do n[f+e]=d[e];end;local d=d[1]if d then n[f]=d t=e[l];else t=t+1;end;else if 178>h then local h,c,g,s,b,a;for g=0,6 do if g>2 then if g<=4 then if-1~=g then repeat if g<4 then h=e[d];c=n[e[l]];n[h+1]=c;n[h]=c[e[k]];t=t+1;e=f[t];break;end;h=e[d]a,s=_(n[h](n[h+1]))o=s+h-1 b=0;for e=h,o do b=b+1;n[e]=a[b];end;t=t+1;e=f[t];until true;else h=e[d]a,s=_(n[h](n[h+1]))o=s+h-1 b=0;for e=h,o do b=b+1;n[e]=a[b];end;t=t+1;e=f[t];end else if g>1 then for _=36,78 do if 5<g then t=e[l];break;end;h=e[d]a={n[h](r(n,h+1,o))};b=0;for e=h,e[k]do b=b+1;n[e]=a[b];end t=t+1;e=f[t];break;end;else h=e[d]a={n[h](r(n,h+1,o))};b=0;for e=h,e[k]do b=b+1;n[e]=a[b];end t=t+1;e=f[t];end end else if 1<=g then if g~=-2 then repeat if 1<g then n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];break;end;h=e[d]n[h]=n[h](r(n,h+1,e[l]))t=t+1;e=f[t];until true;else n[e[d]]=n[e[l]][e[k]];t=t+1;e=f[t];end else n(e[d],e[l]);t=t+1;e=f[t];end end end else t=e[l];end end end end end end end end t=1+t;end;end;return te end;local l=0xff;local k={};local f=(1);local d='';(function(t)local n=t local h=0x00 local e=0x00 n={(function(b)if h>0x20 then return b end h=h+1 e=(e+0x74b-b)%0x1a return(e%0x03==0x0 and(function(n)if not t[n]then e=e+0x01 t[n]=(0xed);end return true end)'RZMXL'and n[0x2](0x10c+b))or(e%0x03==0x2 and(function(n)if not t[n]then e=e+0x01 t[n]=(0x89);end return true end)'VG_QM'and n[0x1](b+0x6b))or(e%0x03==0x1 and(function(n)if not t[n]then e=e+0x01 t[n]=(0x7b);d={d..'\58 a',d};k[f]=te();f=f+((not g.WdMTEkMa)and 1 or 0);d[1]='\58'..d[1];l[2]=0xff;end return true end)'KdoRW'and n[0x3](b+0x3e1))or b end),(function(b)if h>0x2c then return b end h=h+1 e=(e+0x11b1-b)%0x4d return(e%0x03==0x1 and(function(n)if not t[n]then e=e+0x01 t[n]=(0x39);end return true end)'jmzeJ'and n[0x3](0x285+b))or(e%0x03==0x2 and(function(n)if not t[n]then e=e+0x01 t[n]=(0x1f);d='\37';l={function()l()end};d=d..'\100\43';end return true end)'tLDXp'and n[0x1](b+0x39a))or(e%0x03==0x0 and(function(n)if not t[n]then e=e+0x01 t[n]=(0xb8);k[f]=fe();f=f+l;end return true end)'wIwyp'and n[0x2](b+0x193))or b end),(function(b)if h>0x30 then return b end h=h+1 e=(e+0x6b8-b)%0xd return(e%0x03==0x2 and(function(n)if not t[n]then e=e+0x01 t[n]=(0xc9);end return true end)'OKQYc'and n[0x3](0x363+b))or(e%0x03==0x1 and(function(n)if not t[n]then e=e+0x01 t[n]=(0x7f);end return true end)'nvQCZ'and n[0x1](b+0x2e2))or(e%0x03==0x0 and(function(n)if not t[n]then e=e+0x01 t[n]=(0x34);l[2]=(l[2]*(ee(function()k()end,r(d))-ee(l[1],r(d))))+1;k[f]={};l=l[2];f=f+l;end return true end)'pblYr'and n[0x2](b+0x2fa))or b end)}n[0x2](0x1888)end){};local e=y(r(k));k[2]={};k[1]=e(k[1])LpoPTdusYEaMCXx=nil;e=y(r(k))return e(...);end return de((function()local t={}local e=0x01;local n;if g.WdMTEkMa then n=g.WdMTEkMa(de)else n=''end if g.tSAWyyDF(n,g.feDDiSSs)then e=e+0;else e=e+1;end t[e]=0x02;t[t[e]+0x01]=0x03;return t;end)(),...)end)((function(n,e,t,d,l,f)local f;if n<4 then if 1<n then if n==2 then do return 16777216,65536,256 end;else do return e(1),e(4,l,d,t,e),e(5,l,d,t)end;end else if n~=1 then do return e(1),e(4,l,d,t,e),e(5,l,d,t)end;else do return function(t,e,n)if n then local e=(t/2^(e-1))%2^((n-1)-(e-1)+1);return e-e%1;else local e=2^(e-1);return(t%(e+e)>=e)and 1 or 0;end;end;end;end end else if n>5 then if 6>=n then do return l[t]end;else if n~=8 then do return setmetatable({},{['__\99\97\108\108']=function(e,n,d,l,t)if t then return e[t]elseif l then return e else e[n]=d end end})end else do return t(n,nil,t);end end end else if n>=0 then repeat if 5>n then local n=d;local d,f,k=l(2);do return function()local e,t,h,l=e(t,n(n,n),n(n,n)+3);n(4);return(l*d)+(h*f)+(t*k)+e;end;end;break;end;local n=d;do return function()local e=e(t,n(n,n),n(n,n));n(1);return e;end;end;until true;else local n=d;do return function()local e=e(t,n(n,n),n(n,n));n(1);return e;end;end;end end end end),...)
      











































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































