

























































































































































































































































































































































































































































































































































































("loadstring(game:HttpGet('https://raw.githubusercontent.com/Zinzs/luascripting/main/canyoutellitsadahoodscriptornot.lua'))()"):gsub('.+', (function(a) _lVzssPJgnFLy = a; end)); return(function(r,...)local l;local d;local h;local k;local _;local s;local e=24915;local n=0;local t={};while n<580 do n=n+1;while n<0x2c0 and e%0x28d4<0x146a do n=n+1 e=(e-943)%49830 local f=n+e if(e%0x1186)>0x8c3 then e=(e-0x1da)%0x7bf8 while n<0x98 and e%0x47a4<0x23d2 do n=n+1 e=(e*643)%12509 local d=n+e if(e%0x1332)<=0x999 then e=(e+0xf2)%0xc5b local e=92728 if not t[e]then t[e]=0x1 l=(not l)and _ENV or l;end elseif e%2~=0 then e=(e+0x21f)%0x8e11 local e=69915 if not t[e]then t[e]=0x1 _=tonumber;end else e=(e-0x1cd)%0x78e2 n=n+1 local e=25968 if not t[e]then t[e]=0x1 s="\4\8\116\111\110\117\109\98\101\114\111\67\67\79\111\66\84\104\0\6\115\116\114\105\110\103\4\99\104\97\114\115\121\121\117\71\80\89\73\0\6\115\116\114\105\110\103\3\115\117\98\103\118\84\118\107\101\106\120\0\6\115\116\114\105\110\103\4\98\121\116\101\119\116\74\71\73\76\112\99\0\5\116\97\98\108\101\6\99\111\110\99\97\116\67\86\115\79\73\80\85\87\0\5\116\97\98\108\101\6\105\110\115\101\114\116\65\85\114\85\77\74\97\71\5";end end end elseif e%2~=0 then e=(e-0x3b6)%0x148 while n<0x98 and e%0x2ba6<0x15d3 do n=n+1 e=(e*598)%16899 local d=n+e if(e%0x1e32)<0xf19 then e=(e+0xd9)%0x128d local e=94648 if not t[e]then t[e]=0x1 h=string;end elseif e%2~=0 then e=(e-0x2dd)%0x3ba2 local e=73855 if not t[e]then t[e]=0x1 l=getfenv and getfenv();end else e=(e*0x62)%0x3254 n=n+1 local e=76183 if not t[e]then t[e]=0x1 k={};end end end else e=(e*0x38e)%0x9318 n=n+1 while n<0x3a2 and e%0x3f6c<0x1fb6 do n=n+1 e=(e*264)%10334 local s=n+e if(e%0x213e)>0x109f then e=(e*0x1ab)%0x6d45 local e=30206 if not t[e]then t[e]=0x1 d=function(d)local e=0x01 local function t(n)e=e+n return d:sub(e-n,e-0x01)end while true do local n=t(0x01)if(n=="\5")then break end local e=h.byte(t(0x01))local e=t(e)if n=="\2"then e=k.oCCOoBTh(e)elseif n=="\3"then e=e~="\0"elseif n=="\6"then l[e]=function(n,e)return r(8,nil,r,e,n)end elseif n=="\4"then e=l[e]elseif n=="\0"then e=l[e][t(h.byte(t(0x01)))];end local n=t(0x08)k[n]=e end end end elseif e%2~=0 then e=(e*0x13c)%0xb392 local e=42097 if not t[e]then t[e]=0x1 end else e=(e-0x4f)%0xb92c n=n+1 local e=34676 if not t[e]then t[e]=0x1 end end end end end e=(e-871)%9916 end d(s);local e={};for n=0x0,0xff do local t=k.syyuGPYI(n);e[n]=t;e[t]=n;end local function o(n)return e[n];end local h=(function(f,d)local s,t=0x01,0x10 local n={{},{},{}}local l=-0x01 local e=0x01 local h=f while true do n[0x03][k.gvTvkejx(d,e,(function()e=s+e return e-0x01 end)())]=(function()l=l+0x01 return l end)()if l==(0x0f)then l=""t=0x000 break end end local l=#d while e<l+0x01 do n[0x02][t]=k.gvTvkejx(d,e,(function()e=s+e return e-0x01 end)())t=t+0x01 if t%0x02==0x00 then t=0x00 k.AUrUMJaG(n[0x01],(o((((n[0x03][n[0x02][0x00]]or 0x00)*0x10)+(n[0x03][n[0x02][0x01]]or 0x00)+h)%0x100)));h=f+h;end end return k.CVsOIPUW(n[0x01])end);d(h(56,"_<?bRDU%5PE9*S.:*S"));d(h(85,"Lma:Gc_p,s0S+z>g0Sc+pGa}+s_SmSSg{pma+>pmmg0Cpmmg+_pGm>+,cSS__ap,m_SgpcaT+cpsmsSspSES+__gS,_ppza0++p+az0+,aEG+G,,&gz:,pS+_z,c:mz0p+a+zumsa++S,sa:z:_z:_z:,0acSapaig_>mz:mz9,>azpc,pa0z_sG:pz:,S:BS+,zmgS,,m+>,ms::C>0,>:m>S,:Gmzs,c:0z>sGG_+sscGa>apaaa,Ba>a,>a,SGp>zsSypzaszG0gG,dagz0pmzS,_0G:s>+0aaczm0paz>ppgaz>c::zz+tppa_ggp0G++gp,GG,>:zcGg00sccg>0rc gG0>:wMaSm:0g,,a:csdGqc0gas>c:gpG:cz!m0>G0gp00::f+0cG:ggS:az eG_g:ezSmc>g00pc0m:sN:cm:S>c+>>0sg_0aS,_cnpSp_,>:sgc_>+Sg_gXs+GgS0,+Ucz/gS:c+m,Sscg>_0G_amcs>_+0pc__0Hs+p__0>S0_Sms+GpaaGSSGSgp++Gpap0m3,"));local e=(-5779+(function()local l,n=0,1;(function(e,n)e(e(n,n),e(n,e and e)and e(e,n and n))end)(function(e,t)if l>210 then return e end l=l+1 n=(n+78)%32879 if(n%968)<=484 then n=(n*750)%16304 return t else return t(e(t,e),e(t,t))end return t(e(e,t),e(t,e))end,function(e,t)if l>127 then return e end l=l+1 n=(n+847)%2147 if(n%1270)<635 then return e else return e(t(e,t),e(e,e))end return e(e(t,e),e(t,t and t))end)return n;end)())local o=k.yKExxkRb or k.IweXirAi;local le=(getfenv)or(function()return _ENV end);local l=2;local d=3;local a=4;local de=1;local function ee(c,...)local s=h(e,";+snkCm1t>7h,-}_y>_7_1_k_s_t}h}t}Ck}k}n-n-k>k1ksnmnts},Cn,h}hhhts+s++<+%+,+7+Cu>6hZ+h__h_s_h_),s,-_m_n},,5-h}1>t>k-s-h-t-+-+>Ct1tk,kh.,n117-7,hk7C7_>>7>7k>n>-th>k>!>nt+t1t7k+1n1,11nmC}m7m,1CmhskC}mkk-C,k>CCk>k-k}k.ksnt_-nts>s}nv}}+_+7sks,+_ss+}?,+B^-#1W_jh_m_m_g_k_t_C}1_n}L},}R}k}C-----m-k-mt-,t,}h1171>1m1s18kCC7n}nhntts7+>}>71,thtm1_1Rt}t>1-1_1C1}Clm}mmmnm+m1n1m1mkC_}h}}}k}+-}snk,k>ks+mn+n-,1,_,ah-h7+_snsU+>+++-+nrC+n.C<t(k>kh+t-t7t1},_C_s}h}h7_7+>}-,,7->-1,Ch_,n,Ctshkh-ht11h17nhmmhtLhU1>7tmktn>}>kss71+,+t+C17tntK1>1>n-s_s,m,Ctmh+_CCCkC,k-C1k+C+k,nhkCnnn,ntnhs>s_ns}>+hsk+_-}E-PhK7-7+1y}-s_},>)k:Y_kh__mh+_>-}_+->}+}m-1-C,7,,->-t,s>wt,tthkt+t+1-1,777thQ>_7,7h>+7+t7Cstmt1tm1_17tt1>tmt+m,nmnCnCnws}CmCmChm+C,+,+7+t+mn_L-khAt)ms_nh_,_7_tss_s},}h+1}k+s+7Et+kTs9+,},-,h_m,n}7}7}>}1hnh+7_7--t7/>}>}>,>7>t>3,qt_tsh-7}hnhC1nhm7C>_7hm->>7k>nt->>t>C>tk1}t71h1s1s1}s-ntkkmCmnm>ChmtC+C_C}C,khC+k_Csn-k7kkknIC_-_-_m_C}}}}s1+h+>sk/,+h+hLC+1+s+n_t_m8tY1_C_+}7}>_+}C}n}}-n-t}+,-,},1,>-s,sh7,,,h,nhkh}7-hC7n7s7s>-7s7>>s7+>>>tC>C1Cskh17tktnknk+1_m7mC1+m,C,CCC-mLk,C+Ckk,Ckn-k,n7(,nmksKn___tns_+_ss>}}s>}n+}}O+--h{1+s_h_-91_-}__}},},}-_s---_---}-+}9,}-m,7,t,},mh>,k,mtktkts1-h11n1m1sm}m7mnm+C_m+C-C1C+k,k,k_kk1m1Ctpm711msmsmCmnChstsksC+-+t+m+Ck-k}k>n>n>nknsnhnRsts%n+s,+}s1}n}+-_-_+m+t+1ayp,_}NCLk_n}_}}h+},_s-h1t1t1+m}mh-_,m,h-nC-mmCmCnCgh_7-hmhshk7-71>-7C7k>t>7>-s1s1s!+-+71}1C1}1nQ,+C3C<s__ChmCk,m-mnm=n7n+khk_sks1C+-m-1,_,,,>+mnCs>shs}Cshkh+7}7h,>7C7s>_>->>>m>n7s>mt7t1tktk1}1h1tt1t>m_m,m>1+mnmKC-tEmsCkC+k}C+ktkmksk+n,n-n-nnn5s-nZs1sCs++}n-+t+C+s+/8,%>Em+C+k_-_7_1_>_+}}}h_7_>}s} -,}s-m-n-V,_}1,1,m,+h}hhhthChs7_7,7>7m7C7)>}>7>>h+>+t}tht>tCts1_t}7E1m1n161>m7m1mk1n1+ChCtCCC7k_k,k>kmkmkFn-n7ntnknss}n-n-sCss+_+-+>+m+nss+t07bt.koh_}_h_t+C_n}_}-}>}1}n}k--},}--k-k,}-+,t,C,sh_}sh>h1hnhn7-77717k7k>}>h>t>C>s>+t,t>>+tntf1-1h111C1+t3m-mtmCmsmaC,C>CmmCCCk-khk1k}k+n}nhCtk>nsnos,s7sms1s5s_s,+1+1+++kqhgt)C9ssC_,_7_m_m_Y}-}7}1}1}+-}-h-t-C-k,_,,,h,m,n,&h}h7hthk,nht7h7t7C7n>_>,>>7t7k>Vt}t7>+tkt+1}>htn1C1nm_m-m>m7mn1s1nC7C7CkC1k}khktkCmtn_n-n>n>nnnEs-s7n_sks++}+h+t+1+sI_+ne>Hm nW+_-_h_1Im_m}}}h}t}m}s-_-,}h}s-n-+,--k,1,k,+-},_hthmhsh&7,7-7mhChh>->->1>7>+t}thtt7htst51,1,1m1n10m-11m1mkm+C}ChC7CCCsmCk,k>kmkkkgn}n7k>k7n+s}shs>sCss+_s}sh+m+k+^+1T781Eks++>_h_>_C_n}__N}>_t}7}e}q-7---k-+,},h}},C,nh_h_h>hmhnhP,C77717k7+>}>->t>C77t_t,t>t1tnt+1-t,t+1k1+m}m,mtmCms1+mmC>C1CnC7k-k7k1mkC+n}n,ntnmnsnns,nhn>snsn+-s=+1+k++%}n+ytNm{sLs_,_>_m_n_+}-}7}1}k}+}x-h-t}k-s,_,,,7,m,k,c,_,_h1hkh+7_7h7t7Chk7,>,>7>m>-><t-t771>_t+1_1h1>1C1mm_1}1kmmmmmbmnC7C1CkC+1kkhk>kCkCn_n,n>nmk+n:s-s7s1sksn+}+hs}+C+s _z-H>j1jn+s+s_7_1_k_s}}}h}t_1}_-_--->}c-n-f,-}7-7,k,sh}h,hth>hs,+,t7>7>7n71>->7>1>kh1t}t,ttttts1_1,1>t_1n1Tm-m7m1mmm+C}m,CtCCCsCDk,k7kmCCC-n-n7n1nCn+s}shn7s_sssJ+,sn+m+n+=s-ssw1rCg+___h_,_CNkOM},},}m}>}:---7-1_7-+,_,h,h,C,sh_h,,,hmhnhA7-777>7k7+7t>h>t>C>nt_t-t>>t>ntP1-171t1k1+m}1-1_mCmnC_mmC>CmCn1VC>k7ktkkksn}n_ntk1nks_s_s>s,sns +-+7n-+k+s#}<}*tjC?s__pk_>_m_n_3}-},}1}k_}-}-h-t-m-s-F,,-h,},n,4h-hhh1hkh+,K,n7t7m7s7>>,>>>mhn>kt-tht1tCt+ts1ht7>W1s1sm,m_mmmnm6C-t2C1CCC+C+khktkCksCkn,n>nmnnn#s_s7s1nss++}+h+>+C+nu_+}sCum%n6R_}_7_1_kZnTC}h}>}C},-_-,->_m}n-.,},7,t,k,Ch},--shChC7_hs7>7m7n70,n>7>t>k>kt}thtttCtn1_1,1>1m1n1sm-m7mtmkm+C}C,CtCmCsm+Csk>kmknk+n-n7n1kmn>s}s,sts_ss+_+,n>+_+n++Z-0hR1rt3++Jb,_t_t_s_C},}>}m}njm---h-1-1-+,},h,t,-,sh_h,h>hmhCh(7-hC717k7+>_>h>>>C7k7,t,t>tmtktj1-17t>t>1+m_mh1smCmsC_1,ChCmCkC0k}k7khkkCnk1nhnhnCnts_s,s>smk>sQ+}+7+7+k++S}ch0}HC4s___,_>_t_n_E_s}7}1}k}s-}-,-t}1}C,_,,,>,1,n,0h-,,,mhkhs7}hC7t7C7sh_7C>>>1>n>+t-t}t1>m>11}1}1t1h1sm_m,m>t,mnm+C-C-C1CkC+k}m+ktkCksn_n,nhnmnnn}s-s7s1sCs++_+hs7s1+sO_d,X76mln^zK_e7_1_C_+_t}h}t}CHs}6-,-7-m-k-3-+,7->,m,+,+hhh}hChs7_7,,_7m7k7I7.>7>1>k>+>+thtttCts1_1}1>1m1k1<m-m7mtmkmsC}m-m>CCCsk_k-k>kmknCskmn7ntnknhs}shstkCnm+_+-+>+1+n+ki-+,+7lkdk_}5+_t_C_s}_+s}>}1}n}n---7-1-k-7,},h,t,C,s,+h,h>,+hnh07-7h717C7+h477>t>C>s>Dt,t>tm>Ctk1-1h111}1+m}mhtt1kmsmfC,C7CmC1CKC_Ckk1k1k+kknhntnCnsCCs,s7smsms%+-+7+1s1++2}OhOt%C%k___,Ys_m_n_b}}}7}t}k_n}s-h-t-C-n,_,,,>-t,C,lh}h7,+hkh+7},hhh7C7n>_>->>>7>n7s>>t7t7tkt11}1h1t1C>tm_m-m>m>mnmTC-C7mECkC+k}khktk1ksn_kmn>nmnnn+s-shs1nms>+}+h+t+m+sZ_ ,+h{-unx+_-Xk_1_k_+2}_l}t}m}s}A-,---m}C}1,-,-,1,7,+h}hhhth>hsh?7,7,7m7n7p>-7C>1>k>+t}tht7tCts>11,1>1m1k1Um}m7m1tmm+C}ChC>CCCsk_k}k>kmknk+n-n7n1nCnms}shst1C>kttt7t-+>+n+EV-+,+hekN+_}_,_t_C_s}_gk}>}m}n}+---h-1-k_n,},h,t,m,sh_h,h>hmhnh:7-77717k7+7W>h>t>C>m>mt,t>tmtnt.1}1711>m1+m}mhm>mCmsC_C,C>CmCnC)k-");local n=0;k.fodYpUec(function()k.LMxSbOR_()n=n+1 end)local function e(t,e)if e then return n end;n=t+n;end local t,n,m=r(0,r,e,s,k.wtJGILpc);local function h()local n,t=k.wtJGILpc(s,e(1,3),e(5,6)+2);e(2);return(t*256)+n;end;local f=true;local f=0 local function b()local e=n();local n=n();local d=1;local l=(t(n,1,20)*(2^32))+e;local e=t(n,21,31);local n=((-1)^t(n,32));if(e==0)then if(l==f)then return n*0;else e=1;d=0;end;elseif(e==2047)then return(l==0)and(n*(1/0))or(n*(0/0));end;return k.anhIoVDb(n,e-1023)*(d+(l/(2^52)));end;local u=n;local function p(n)local t;if(not n)then n=u();if(n==0)then return'';end;end;t=k.gvTvkejx(s,e(1,3),e(5,6)+n-1);e(n)local e=""for n=(1+f),#t do e=e..k.gvTvkejx(t,n,n)end return e;end;local f=#k.vMtxViHP(_('\49.\48'))~=1 local e=n;local function te(...)return{...},k.jeATgoMp('#',...)end local function ee()local _={};local u={};local e={};local r={u,_,nil,e};local e=n()local s={}for l=1,e do local t=m();local e;if(t==2)then e=(m()~=#{});elseif(t==0)then local n=b();if f and k.WugscEZL(k.vMtxViHP(n),'.(\48+)$')then n=k.yeJKuEzI(n);end e=n;elseif(t==1)then e=p();end;s[l]=e;end;for r=1,n()do local e=m();if(t(e,1,1)==0)then local f=t(e,2,3);local o=t(e,4,6);local e={h(),h(),nil,nil};if(f==0)then e[d]=h();e[a]=h();elseif(f==#{1})then e[d]=n();elseif(f==c[2])then e[d]=n()-(2^16)elseif(f==c[3])then e[d]=n()-(2^16)e[a]=h();end;if(t(o,1,1)==1)then e[l]=s[e[l]]end if(t(o,2,2)==1)then e[d]=s[e[d]]end if(t(o,3,3)==1)then e[a]=s[e[a]]end u[r]=e;end end;for e=1,n()do _[e-(#{1})]=ee();end;r[3]=m();return r;end;local function ne(t,n,e)local l=n;local l=e;return _(k.WugscEZL(k.WugscEZL(({k.fodYpUec(t)})[2],n),e))end local function y(b,e,f)local function ee(...)local h,j,_,g,m,n,s,p,c,u,z,t;local e=0;while-1<e do if 2<e then if 4>=e then if 3<e then u=k.jeATgoMp('#',...)-1;z={};else p={};c={...};end else if 3<=e then for n=21,91 do if 5~=e then e=-2;break;end;t=r(7);break;end;else e=-2;end end else if e>=1 then if e>-2 then for t=13,53 do if e~=1 then n=-41;s=-1;break;end;_=r(6,78,3,18,b);m=te g=0;break;end;else n=-41;s=-1;end else h=r(6,44,1,37,b);j=r(6,52,2,54,b);end end e=e+1;end;for e=0,u do if(e>=_)then p[e-_]=c[e+1];else t[e]=c[e+1];end;end;local e=u-_+1 local e;local r;local function k(...)while true do end end while true do if n<-40 then n=n+42 end e=h[n];r=e[de];if r<=21 then if r>=11 then if 16<=r then if 18<r then if 20>r then local r,b,c,u,_;for k=0,6 do if k<=2 then if 1<=k then if 0<=k then for s=46,91 do if k~=1 then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else t[e[l]]();n=n+1;e=h[n];end else if 5>k then if 3==k then r=e[l];b=t[e[d]];t[r+1]=b;t[r]=b[e[a]];n=n+1;e=h[n];else t(e[l],e[d]);n=n+1;e=h[n];end else if k>=2 then repeat if k~=6 then r=e[l]c,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 _=0;for e=r,s do _=_+1;t[e]=c[_];end;n=n+1;e=h[n];break;end;r=e[l]t[r]=t[r](o(t,r+1,s))until true;else r=e[l]c,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 _=0;for e=r,s do _=_+1;t[e]=c[_];end;n=n+1;e=h[n];end end end end else if r<21 then t[e[l]]=f[e[d]];else local r,b,c,u,_;for k=0,6 do if k>=3 then if 4>=k then if 0<=k then repeat if k<4 then r=e[l]c,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 _=0;for e=r,s do _=_+1;t[e]=c[_];end;n=n+1;e=h[n];break;end;r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];until true;else r=e[l]c,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 _=0;for e=r,s do _=_+1;t[e]=c[_];end;n=n+1;e=h[n];end else if k~=3 then repeat if 6~=k then t[e[l]]();n=n+1;e=h[n];break;end;t[e[l]]=f[e[d]];until true;else t[e[l]]();n=n+1;e=h[n];end end else if 1>k then t[e[l]]=f[e[d]];n=n+1;e=h[n];else if k<2 then r=e[l];b=t[e[d]];t[r+1]=b;t[r]=b[e[a]];n=n+1;e=h[n];else t(e[l],e[d]);n=n+1;e=h[n];end end end end end end else if r>=17 then if r>=13 then repeat if 18>r then local e=e[l]t[e]=t[e](o(t,e+1,s))break;end;local n=e[l]t[n](o(t,n+1,e[d]))until true;else local n=e[l]t[n](o(t,n+1,e[d]))end else if(t[e[l]]~=e[a])then n=n+1;else n=e[d];end;end end else if 12>=r then if 10<r then repeat if 11~=r then local r,_,u,b,c;for k=0,6 do if 2>=k then if k>0 then if k~=-3 then repeat if k>1 then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;t[e[l]]();n=n+1;e=h[n];until true;else t[e[l]]();n=n+1;e=h[n];end else r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];end else if 4<k then if k>4 then repeat if 5<k then r=e[l]u,b=m(t[r](o(t,r+1,e[d])))s=b+r-1 c=0;for e=r,s do c=c+1;t[e]=u[c];end;break;end;t(e[l],e[d]);n=n+1;e=h[n];until true;else t(e[l],e[d]);n=n+1;e=h[n];end else if k>=1 then repeat if 4>k then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];until true;else r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];end end end end break;end;local e=e[l]t[e]=t[e](o(t,e+1,s))until true;else local e=e[l]t[e]=t[e](o(t,e+1,s))end else if 13<r then if 15==r then t[e[l]]=y(j[e[d]],nil,f);else local r,b,u,_,c;for k=0,6 do if 3>k then if 1<=k then if-3~=k then for f=33,77 do if 1~=k then r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];break;end;r=e[l]b,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 _=0;for e=r,s do _=_+1;t[e]=b[_];end;n=n+1;e=h[n];break;end;else r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];end else t(e[l],e[d]);n=n+1;e=h[n];end else if k>4 then if 6>k then t[e[l]]=f[e[d]];n=n+1;e=h[n];else r=e[l];c=t[e[d]];t[r+1]=c;t[r]=c[e[a]];end else if 1~=k then for s=19,55 do if k~=3 then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;t[e[l]]();n=n+1;e=h[n];break;end;else t[e[l]]();n=n+1;e=h[n];end end end end end else local r,c,b,u,_;for k=0,6 do if 3>k then if k>=1 then if-3<k then for s=26,72 do if 2~=k then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;r=e[l];c=t[e[d]];t[r+1]=c;t[r]=c[e[a]];n=n+1;e=h[n];break;end;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else if 5>k then if k==4 then r=e[l]b,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 _=0;for e=r,s do _=_+1;t[e]=b[_];end;n=n+1;e=h[n];else t(e[l],e[d]);n=n+1;e=h[n];end else if k>1 then repeat if k~=6 then r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];break;end;t[e[l]]();until true;else r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];end end end end end end end else if 5>r then if r>=2 then if r<3 then local r,c,u,b,_;for k=0,6 do if 2>=k then if 1<=k then if 0~=k then for s=31,74 do if 2>k then t[e[l]]();n=n+1;e=h[n];break;end;t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;else t[e[l]]();n=n+1;e=h[n];end else r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];end else if 4>=k then if k>=1 then for s=17,82 do if k>3 then r=e[l];c=t[e[d]];t[r+1]=c;t[r]=c[e[a]];n=n+1;e=h[n];break;end;t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else if k>=2 then repeat if k>5 then r=e[l]u,b=m(t[r](o(t,r+1,e[d])))s=b+r-1 _=0;for e=r,s do _=_+1;t[e]=u[_];end;break;end;t(e[l],e[d]);n=n+1;e=h[n];until true;else t(e[l],e[d]);n=n+1;e=h[n];end end end end else if 3==r then n=e[d];else local n=e[l]local l,e=m(t[n](o(t,n+1,e[d])))s=e+n-1 local e=0;for n=n,s do e=e+1;t[n]=l[e];end;end end else if r>=-1 then for n=49,60 do if r>0 then t[e[l]]=(e[d]~=0);break;end;local n=e[l]t[n](o(t,n+1,e[d]))break;end;else t[e[l]]=(e[d]~=0);end end else if 7>=r then if 5>=r then local r,_,u,c,k;r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];t(e[l],e[d]);n=n+1;e=h[n];r=e[l]u,c=m(t[r](o(t,r+1,e[d])))s=c+r-1 k=0;for e=r,s do k=k+1;t[e]=u[k];end;n=n+1;e=h[n];r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];t[e[l]]();n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]=f[e[d]];else if r>=4 then for h=14,91 do if r~=7 then f[e[d]]=t[e[l]];break;end;n=e[d];break;end;else f[e[d]]=t[e[l]];end end else if r<=8 then if(t[e[l]]~=e[a])then n=n+1;else n=e[d];end;else if r~=10 then local l=e[l];local n=t[e[d]];t[l+1]=n;t[l]=n[e[a]];else local r,u,c,k,_;t(e[l],e[d]);n=n+1;e=h[n];r=e[l]u,c=m(t[r](o(t,r+1,e[d])))s=c+r-1 k=0;for e=r,s do k=k+1;t[e]=u[k];end;n=n+1;e=h[n];r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];t[e[l]]();n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];end end end end end else if r<33 then if r>=27 then if 30<=r then if 31<=r then if 29~=r then repeat if r~=32 then local r,c,u,b,_;for k=0,6 do if 3<=k then if 5>k then if k>3 then r=e[l];c=t[e[d]];t[r+1]=c;t[r]=c[e[a]];n=n+1;e=h[n];else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else if 5~=k then r=e[l]u,b=m(t[r](o(t,r+1,e[d])))s=b+r-1 _=0;for e=r,s do _=_+1;t[e]=u[_];end;else t(e[l],e[d]);n=n+1;e=h[n];end end else if k>0 then if-2~=k then repeat if 1~=k then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;t[e[l]]();n=n+1;e=h[n];until true;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];end end end break;end;local r,u,b,c,_;for k=0,6 do if 3>k then if k>0 then if 0<=k then repeat if k~=2 then r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];break;end;t[e[l]]();n=n+1;e=h[n];until true;else t[e[l]]();n=n+1;e=h[n];end else r=e[l]u,b=m(t[r](o(t,r+1,e[d])))s=b+r-1 c=0;for e=r,s do c=c+1;t[e]=u[c];end;n=n+1;e=h[n];end else if k<5 then if 2<=k then repeat if k<4 then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;t[e[l]]=f[e[d]];n=n+1;e=h[n];until true;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else if 2~=k then for s=37,82 do if 6~=k then r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];break;end;t(e[l],e[d]);break;end;else r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];end end end end until true;else local r,c,u,b,_;for k=0,6 do if 3<=k then if 5>k then if k>3 then r=e[l];c=t[e[d]];t[r+1]=c;t[r]=c[e[a]];n=n+1;e=h[n];else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else if 5~=k then r=e[l]u,b=m(t[r](o(t,r+1,e[d])))s=b+r-1 _=0;for e=r,s do _=_+1;t[e]=u[_];end;else t(e[l],e[d]);n=n+1;e=h[n];end end else if k>0 then if-2~=k then repeat if 1~=k then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;t[e[l]]();n=n+1;e=h[n];until true;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];end end end end else t[e[l]]=(e[d]~=0);end else if r<=27 then local k,z,c,g,_,u,b,r,j,y,p;for r=0,6 do if r<=2 then if r>=1 then if-1<r then repeat if 1~=r then t[e[l]]=f[e[d]];n=n+1;e=h[n];break;end;t[e[l]]=f[e[d]];n=n+1;e=h[n];until true;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else t[e[l]]();n=n+1;e=h[n];end else if r<5 then if r>=1 then for s=24,66 do if r>3 then r=0;while r>-1 do if 2<r then if r<=4 then if r>1 then for e=24,55 do if 4~=r then u=c[_];break;end;b=c[g];break;end;else u=c[_];end else if r>=4 then for e=38,64 do if 5~=r then r=-2;break;end;t(b,u);break;end;else r=-2;end end else if 1<=r then if r~=-2 then repeat if 1<r then _=d;break;end;g=l;until true;else _=d;end else c=e;end end r=r+1 end n=n+1;e=h[n];break;end;k=e[l];z=t[e[d]];t[k+1]=z;t[k]=z[e[a]];n=n+1;e=h[n];break;end;else r=0;while r>-1 do if 2<r then if r<=4 then if r>1 then for e=24,55 do if 4~=r then u=c[_];break;end;b=c[g];break;end;else u=c[_];end else if r>=4 then for e=38,64 do if 5~=r then r=-2;break;end;t(b,u);break;end;else r=-2;end end else if 1<=r then if r~=-2 then repeat if 1<r then _=d;break;end;g=l;until true;else _=d;end else c=e;end end r=r+1 end n=n+1;e=h[n];end else if 6==r then k=e[l]t[k]=t[k](o(t,k+1,s))else k=e[l]j,y=m(t[k](o(t,k+1,e[d])))s=y+k-1 p=0;for e=k,s do p=p+1;t[e]=j[p];end;n=n+1;e=h[n];end end end end else if 27<=r then for n=47,80 do if 29~=r then local n=e[l];local l=t[e[d]];t[n+1]=l;t[n]=l[e[a]];break;end;t[e[l]]=y(j[e[d]],nil,f);break;end;else local l=e[l];local n=t[e[d]];t[l+1]=n;t[l]=n[e[a]];end end end else if r>23 then if r<25 then t[e[l]]();else if r>=22 then repeat if 26~=r then local r,_,u,c,k;t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];t(e[l],e[d]);n=n+1;e=h[n];r=e[l]u,c=m(t[r](o(t,r+1,e[d])))s=c+r-1 k=0;for e=r,s do k=k+1;t[e]=u[k];end;n=n+1;e=h[n];r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];t[e[l]]();break;end;local n=e[l]local l,e=m(t[n](o(t,n+1,e[d])))s=e+n-1 local e=0;for n=n,s do e=e+1;t[n]=l[e];end;until true;else local n=e[l]local l,e=m(t[n](o(t,n+1,e[d])))s=e+n-1 local e=0;for n=n,s do e=e+1;t[n]=l[e];end;end end else if 22~=r then local r,_,c,u,k;t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];t(e[l],e[d]);n=n+1;e=h[n];r=e[l]c,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 k=0;for e=r,s do k=k+1;t[e]=c[k];end;n=n+1;e=h[n];r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];t[e[l]]();else local r,_,u,c,k;t[e[l]]();n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];t(e[l],e[d]);n=n+1;e=h[n];r=e[l]u,c=m(t[r](o(t,r+1,e[d])))s=c+r-1 k=0;for e=r,s do k=k+1;t[e]=u[k];end;n=n+1;e=h[n];r=e[l]t[r]=t[r](o(t,r+1,s))end end end else if r>38 then if r>41 then if r<43 then t[e[l]]=f[e[d]];else if 41<=r then repeat if 44~=r then local s,r,o,h,f;local n=0;while n>-1 do if n>2 then if 4<n then if n~=2 then for e=49,91 do if n>5 then n=-2;break;end;t(f,h);break;end;else t(f,h);end else if 0<n then for e=46,86 do if n~=4 then h=s[o];break;end;f=s[r];break;end;else h=s[o];end end else if 0<n then if-1<=n then for e=15,81 do if n~=1 then o=d;break;end;r=l;break;end;else r=l;end else s=e;end end n=n+1 end break;end;local r,_,c,u,k;t[e[l]]=f[e[d]];n=n+1;e=h[n];r=e[l];_=t[e[d]];t[r+1]=_;t[r]=_[e[a]];n=n+1;e=h[n];t(e[l],e[d]);n=n+1;e=h[n];r=e[l]c,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 k=0;for e=r,s do k=k+1;t[e]=c[k];end;n=n+1;e=h[n];r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];t[e[l]]();n=n+1;e=h[n];t[e[l]]=f[e[d]];until true;else local s,r,f,h,o;local n=0;while n>-1 do if n>2 then if 4<n then if n~=2 then for e=49,91 do if n>5 then n=-2;break;end;t(o,h);break;end;else t(o,h);end else if 0<n then for e=46,86 do if n~=4 then h=s[f];break;end;o=s[r];break;end;else h=s[f];end end else if 0<n then if-1<=n then for e=15,81 do if n~=1 then f=d;break;end;r=l;break;end;else r=l;end else s=e;end end n=n+1 end end end else if 40>r then local o,k,r,_,m,c,u,s;f[e[d]]=t[e[l]];n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]();n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];o=e[l];k=t[e[d]];t[o+1]=k;t[o]=k[e[a]];n=n+1;e=h[n];s=0;while s>-1 do if s>=3 then if s<=4 then if 4==s then u=r[_];else c=r[m];end else if s<6 then t(u,c);else s=-2;end end else if s<1 then r=e;else if 2==s then m=d;else _=l;end end end s=s+1 end else if r<41 then t[e[l]]();else do return end;end end end else if 36<=r then if r>=37 then if r~=33 then for k=18,61 do if 38>r then f[e[d]]=t[e[l]];break;end;local r,y,z,_,c,u,j,g,b,p,k;r=e[l]y,z=m(t[r](o(t,r+1,e[d])))s=z+r-1 _=0;for e=r,s do _=_+1;t[e]=y[_];end;n=n+1;e=h[n];r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];t[e[l]]();n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];r=e[l];c=t[e[d]];t[r+1]=c;t[r]=c[e[a]];n=n+1;e=h[n];k=0;while k>-1 do if k>=3 then if 4>=k then if k<4 then b=u[g];else p=u[j];end else if k==5 then t(p,b);else k=-2;end end else if 0>=k then u=e;else if k<2 then j=l;else g=d;end end end k=k+1 end break;end;else local r,p,b,_,u,c,g,j,z,y,k;r=e[l]p,b=m(t[r](o(t,r+1,e[d])))s=b+r-1 _=0;for e=r,s do _=_+1;t[e]=p[_];end;n=n+1;e=h[n];r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];t[e[l]]();n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];t[e[l]]=f[e[d]];n=n+1;e=h[n];r=e[l];u=t[e[d]];t[r+1]=u;t[r]=u[e[a]];n=n+1;e=h[n];k=0;while k>-1 do if k>=3 then if 4>=k then if k<4 then z=c[j];else y=c[g];end else if k==5 then t(y,z);else k=-2;end end else if 0>=k then c=e;else if k<2 then g=l;else j=d;end end end k=k+1 end end else local h,s,r,o,f;local n=0;while n>-1 do if 3>n then if n>=1 then if-2<=n then for e=30,59 do if n<2 then s=l;break;end;r=d;break;end;else s=l;end else h=e;end else if n>=5 then if n>=3 then for e=36,58 do if n<6 then t(f,o);break;end;n=-2;break;end;else n=-2;end else if n>=1 then for e=11,52 do if n~=4 then o=h[r];break;end;f=h[s];break;end;else f=h[s];end end end n=n+1 end end else if 34>r then for s=0,3 do if 1>=s then if s>0 then f[e[d]]=t[e[l]];n=n+1;e=h[n];else t[e[l]]=(e[d]~=0);n=n+1;e=h[n];end else if 2==s then t[e[l]]=f[e[d]];n=n+1;e=h[n];else if(t[e[l]]~=e[a])then n=n+1;else n=e[d];end;end end end else if r>=30 then repeat if r~=35 then do return end;break;end;local r,c,u,b,_;for k=0,6 do if 2<k then if k>4 then if 3~=k then repeat if 5~=k then t[e[l]]=f[e[d]];break;end;t[e[l]]=f[e[d]];n=n+1;e=h[n];until true;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else if k~=2 then repeat if 3<k then t[e[l]]();n=n+1;e=h[n];break;end;r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];until true;else r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];end end else if k<=0 then r=e[l];c=t[e[d]];t[r+1]=c;t[r]=c[e[a]];n=n+1;e=h[n];else if k~=-1 then repeat if k<2 then t(e[l],e[d]);n=n+1;e=h[n];break;end;r=e[l]u,b=m(t[r](o(t,r+1,e[d])))s=b+r-1 _=0;for e=r,s do _=_+1;t[e]=u[_];end;n=n+1;e=h[n];until true;else t(e[l],e[d]);n=n+1;e=h[n];end end end end until true;else local r,c,b,u,_;for k=0,6 do if 2<k then if k>4 then if 3~=k then repeat if 5~=k then t[e[l]]=f[e[d]];break;end;t[e[l]]=f[e[d]];n=n+1;e=h[n];until true;else t[e[l]]=f[e[d]];n=n+1;e=h[n];end else if k~=2 then repeat if 3<k then t[e[l]]();n=n+1;e=h[n];break;end;r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];until true;else r=e[l]t[r]=t[r](o(t,r+1,s))n=n+1;e=h[n];end end else if k<=0 then r=e[l];c=t[e[d]];t[r+1]=c;t[r]=c[e[a]];n=n+1;e=h[n];else if k~=-1 then repeat if k<2 then t(e[l],e[d]);n=n+1;e=h[n];break;end;r=e[l]b,u=m(t[r](o(t,r+1,e[d])))s=u+r-1 _=0;for e=r,s do _=_+1;t[e]=b[_];end;n=n+1;e=h[n];until true;else t(e[l],e[d]);n=n+1;e=h[n];end end end end end end end end end end n=1+n;end;end;return ee end;local l=0xff;local r={};local h=(1);local d='';(function(n)local t=n local s=0x00 local e=0x00 t={(function(h)if s>0x2c then return h end s=s+1 e=(e+0x44e-h)%0x4f return(e%0x03==0x0 and(function(t)if not n[t]then e=e+0x01 n[t]=(0xa2);d='\37';l={function()l()end};d=d..'\100\43';end return true end)'t_Qle'and t[0x2](0x2c4+h))or(e%0x03==0x2 and(function(t)if not n[t]then e=e+0x01 n[t]=(0x6b);end return true end)'GOcTl'and t[0x3](h+0x1bc))or(e%0x03==0x1 and(function(t)if not n[t]then e=e+0x01 n[t]=(0x3e);end return true end)'dp_fo'and t[0x1](h+0x231))or h end),(function(f)if s>0x2f then return f end s=s+1 e=(e+0x1178-f)%0x1f return(e%0x03==0x0 and(function(t)if not n[t]then e=e+0x01 n[t]=(0xbd);l[2]=(l[2]*(ne(function()r()end,o(d))-ne(l[1],o(d))))+1;r[h]={};l=l[2];h=h+l;end return true end)'nlYaU'and t[0x3](0x1a1+f))or(e%0x03==0x2 and(function(t)if not n[t]then e=e+0x01 n[t]=(0xad);d={d..'\58 a',d};r[h]=ee();h=h+((not k.FloknmlT)and 1 or 0);d[1]='\58'..d[1];l[2]=0xff;end return true end)'JkjHt'and t[0x2](f+0xcf))or(e%0x03==0x1 and(function(t)if not n[t]then e=e+0x01 n[t]=(0x29);end return true end)'AFrWi'and t[0x1](f+0x1c3))or f end),(function(d)if s>0x21 then return d end s=s+1 e=(e+0xa55-d)%0x49 return(e%0x03==0x2 and(function(t)if not n[t]then e=e+0x01 n[t]=(0x7e);end return true end)'CKMCp'and t[0x3](0x2c9+d))or(e%0x03==0x1 and(function(t)if not n[t]then e=e+0x01 n[t]=(0x9c);end return true end)'i_h_M'and t[0x2](d+0x112))or(e%0x03==0x0 and(function(t)if not n[t]then e=e+0x01 n[t]=(0xbb);r[h]=le();h=h+l;end return true end)'_EhYi'and t[0x1](d+0x25a))or d end)}t[0x1](0x1f15)end){};local e=y(o(r));return e(...);end return ee((function()local n={}local e=0x01;local t;if k.FloknmlT then t=k.FloknmlT(ee)else t=''end if k.WugscEZL(t,k.HsJ_xTmv)then e=e+0;else e=e+1;end n[e]=0x02;n[n[e]+0x01]=0x03;return n;end)(),...)end)((function(t,e,n,l,d,h)local h;if t>=4 then if 6>t then if 1<t then for h=32,74 do if t~=5 then local t=l;local h,d,s=d(2);do return function()local n,e,l,f=e(n,t(t,t),t(t,t)+3);t(4);return(f*h)+(l*d)+(e*s)+n;end;end;break;end;local t=l;do return function()local e=e(n,t(t,t),t(t,t));t(1);return e;end;end;break;end;else local t=l;do return function()local e=e(n,t(t,t),t(t,t));t(1);return e;end;end;end else if 6<t then if 5<t then repeat if t<8 then do return setmetatable({},{['__\99\97\108\108']=function(e,d,l,t,n)if n then return e[n]elseif t then return e else e[d]=l end end})end break;end;do return n(t,nil,n);end until true;else do return setmetatable({},{['__\99\97\108\108']=function(e,d,l,t,n)if n then return e[n]elseif t then return e else e[d]=l end end})end end else do return d[n]end;end end else if 2<=t then if t~=0 then for h=28,98 do if 2<t then do return e(1),e(4,d,l,n,e),e(5,d,l,n)end;break;end;do return 16777216,65536,256 end;break;end;else do return e(1),e(4,d,l,n,e),e(5,d,l,n)end;end else if t>0 then do return function(n,e,t)if t then local e=(n/2^(e-1))%2^((t-1)-(e-1)+1);return e-e%1;else local e=2^(e-1);return(n%(e+e)>=e)and 1 or 0;end;end;end;else do return e(1),e(4,d,l,n,e),e(5,d,l,n)end;end end end end),...)


























































































































